const adjetivos = [
  // BLOQUE 1
  { lema: "aeger", tipo: "adjetivo", raiz: "aegr-", decl: "1.ª y 2.ª", genero: "variable", trad: "enfermo" },
  { lema: "Aegyptius", tipo: "adjetivo", raiz: "Aegypti-", decl: "1.ª y 2.ª", genero: "variable", trad: "egipcio" },
  { lema: "alius", tipo: "adjetivo", raiz: "ali-", decl: "1.ª y 2.ª (Irreg.)", genero: "variable", trad: "otro" },
  { lema: "alter", tipo: "adjetivo", raiz: "alter-", decl: "1.ª y 2.ª (Irreg.)", genero: "variable", trad: "el otro" },
  { lema: "amīcissimus", tipo: "adjetivo", raiz: "amicissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy amigable" },
  { lema: "antīquus", tipo: "adjetivo", raiz: "antiqu-", decl: "1.ª y 2.ª", genero: "variable", trad: "antiguo" },
  { lema: "anxius", tipo: "adjetivo", raiz: "anxi-", decl: "1.ª y 2.ª", genero: "variable", trad: "preocupado" },
  { lema: "āter", tipo: "adjetivo", raiz: "atr-", decl: "1.ª y 2.ª", genero: "variable", trad: "negro" },
  { lema: "attonitus", tipo: "adjetivo", raiz: "attonit-", decl: "1.ª y 2.ª", genero: "variable", trad: "atónito" },
  { lema: "audāx", tipo: "adjetivo", raiz: "audac-", decl: "3.ª", genero: "variable", trad: "audaz" },
  { lema: "benignus", tipo: "adjetivo", raiz: "benign-", decl: "1.ª y 2.ª", genero: "variable", trad: "amable" },
  { lema: "bonus", tipo: "adjetivo", raiz: "bon-", decl: "1.ª y 2.ª", genero: "variable", trad: "bueno" },
  { lema: "callidior", tipo: "adjetivo", raiz: "callidior-", decl: "3.ª (Comp.)", genero: "variable", trad: "más astuto" },
  { lema: "callidus", tipo: "adjetivo", raiz: "callid-", decl: "1.ª y 2.ª", genero: "variable", trad: "astuto" },
  { lema: "cēterī", tipo: "adjetivo", raiz: "ceter-", decl: "1.ª y 2.ª", genero: "variable", trad: "los demás" },
  { lema: "commōtus", tipo: "adjetivo", raiz: "commot-", decl: "1.ª y 2.ª", genero: "variable", trad: "conmovido" },
  { lema: "contentus", tipo: "adjetivo", raiz: "content-", decl: "1.ª y 2.ª", genero: "variable", trad: "satisfecho" },
  { lema: "decem", tipo: "adjetivo", raiz: "decem", decl: "Indeclinable", genero: "variable", trad: "diez" },
  { lema: "dēnsior", tipo: "adjetivo", raiz: "densior-", decl: "3.ª (Comp.)", genero: "variable", trad: "más denso" },
  { lema: "dēnsissima", tipo: "adjetivo", raiz: "densissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy densa" },
  { lema: "dēnsissimus", tipo: "adjetivo", raiz: "densissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy denso" },
  { lema: "dēsertus", tipo: "adjetivo", raiz: "desert-", decl: "1.ª y 2.ª", genero: "variable", trad: "desierto" },
  { lema: "difficilis", tipo: "adjetivo", raiz: "difficil-", decl: "3.ª", genero: "variable", trad: "difícil" },
  { lema: "dīves", tipo: "adjetivo", raiz: "divit-", decl: "3.ª", genero: "variable", trad: "rico" },
  { lema: "doctus", tipo: "adjetivo", raiz: "doct-", decl: "1.ª y 2.ª", genero: "variable", trad: "docto" },
  { lema: "duo", tipo: "adjetivo", raiz: "du-", decl: "Irregular", genero: "variable", trad: "dos" },
  { lema: "ēbrius", tipo: "adjetivo", raiz: "ebri-", decl: "1.ª y 2.ª", genero: "variable", trad: "ebrio" },
  { lema: "expedītus", tipo: "adjetivo", raiz: "expedit-", decl: "1.ª y 2.ª", genero: "variable", trad: "expedito" },
  { lema: "ferōcissimus", tipo: "adjetivo", raiz: "ferocissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy feroz" },
  { lema: "ferōx", tipo: "adjetivo", raiz: "feroc-", decl: "3.ª", genero: "variable", trad: "feroz" },
  { lema: "fidēlis", tipo: "adjetivo", raiz: "fidel-", decl: "3.ª", genero: "variable", trad: "fiel" },
  { lema: "fortior", tipo: "adjetivo", raiz: "fortior-", decl: "3.ª (Comp.)", genero: "variable", trad: "más fuerte" },
  { lema: "fortis", tipo: "adjetivo", raiz: "fort-", decl: "3.ª", genero: "variable", trad: "valiente" },
  { lema: "fortissimus", tipo: "adjetivo", raiz: "fortissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy valiente" },
  { lema: "frāctus", tipo: "adjetivo", raiz: "fract-", decl: "1.ª y 2.ª", genero: "variable", trad: "roto" },
  { lema: "Graeculus", tipo: "adjetivo", raiz: "Graecul-", decl: "1.ª y 2.ª", genero: "variable", trad: "griegucho" },
  { lema: "Graecus", tipo: "adjetivo", raiz: "Graec-", decl: "1.ª y 2.ª", genero: "variable", trad: "griego" },
  { lema: "I", tipo: "adjetivo", raiz: "un-", decl: "1.ª y 2.ª (Irreg.)", genero: "variable", trad: "uno, primero" },
  { lema: "ignāvus", tipo: "adjetivo", raiz: "ignav-", decl: "1.ª y 2.ª", genero: "variable", trad: "cobarde" },
  { lema: "II", tipo: "adjetivo", raiz: "du-", decl: "Irregular", genero: "variable", trad: "dos, segundo" },
  { lema: "immōtus", tipo: "adjetivo", raiz: "immot-", decl: "1.ª y 2.ª", genero: "variable", trad: "inmóvil" },
  { lema: "īnfēlīx", tipo: "adjetivo", raiz: "infelic-", decl: "3.ª", genero: "variable", trad: "infeliz" },
  { lema: "ingēns", tipo: "adjetivo", raiz: "ingent-", decl: "3.ª", genero: "variable", trad: "enorme" },
  { lema: "īnsānus", tipo: "adjetivo", raiz: "insan-", decl: "1.ª y 2.ª", genero: "variable", trad: "loco" },
  { lema: "īrātissimus", tipo: "adjetivo", raiz: "iratissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy enfadado" },
  { lema: "īrātus", tipo: "adjetivo", raiz: "irat-", decl: "1.ª y 2.ª", genero: "variable", trad: "enfadado" },
  { lema: "laetissimus", tipo: "adjetivo", raiz: "laetissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy feliz" },
  { lema: "laetus", tipo: "adjetivo", raiz: "laet-", decl: "1.ª y 2.ª", genero: "variable", trad: "feliz" },
  { lema: "lapideus", tipo: "adjetivo", raiz: "lapide-", decl: "1.ª y 2.ª", genero: "variable", trad: "de piedra" },
  { lema: "Latīnus", tipo: "adjetivo", raiz: "Latin-", decl: "1.ª y 2.ª", genero: "variable", trad: "latino" },
  { lema: "līberālis", tipo: "adjetivo", raiz: "liberal-", decl: "3.ª", genero: "variable", trad: "generoso" },
  { lema: "līberālissimus", tipo: "adjetivo", raiz: "liberalissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy generoso" },
  { lema: "longus", tipo: "adjetivo", raiz: "long-", decl: "1.ª y 2.ª", genero: "variable", trad: "largo" },
  { lema: "magnificus", tipo: "adjetivo", raiz: "magnific-", decl: "1.ª y 2.ª", genero: "variable", trad: "magnífico" },
  { lema: "magnus", tipo: "adjetivo", raiz: "magn-", decl: "1.ª y 2.ª", genero: "variable", trad: "grande" },
  { lema: "maior", tipo: "adjetivo", raiz: "maior-", decl: "3.ª (Comp.)", genero: "variable", trad: "mayor" },
  { lema: "maximus", tipo: "adjetivo", raiz: "maxim-", decl: "1.ª y 2.ª", genero: "variable", trad: "máximo" },
  { lema: "medius", tipo: "adjetivo", raiz: "medi-", decl: "1.ª y 2.ª", genero: "variable", trad: "medio" },
  { lema: "melior", tipo: "adjetivo", raiz: "melior-", decl: "3.ª (Comp.)", genero: "variable", trad: "mejor" },
  { lema: "mendācissimus", tipo: "adjetivo", raiz: "mendacissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy mentiroso" },
  { lema: "meus", tipo: "adjetivo", raiz: "me-", decl: "1.ª y 2.ª", genero: "variable", trad: "mío" },
  { lema: "mīrābilis", tipo: "adjetivo", raiz: "mirabil-", decl: "3.ª", genero: "variable", trad: "extraño" },
  { lema: "miserandus", tipo: "adjetivo", raiz: "miserand-", decl: "1.ª y 2.ª", genero: "variable", trad: "lamentable" },
  { lema: "moribundus", tipo: "adjetivo", raiz: "moribund-", decl: "1.ª y 2.ª", genero: "variable", trad: "moribundo" },
  { lema: "mortuus", tipo: "adjetivo", raiz: "mortu-", decl: "1.ª y 2.ª", genero: "variable", trad: "muerto" },
  { lema: "multī", tipo: "adjetivo", raiz: "mult-", decl: "1.ª y 2.ª", genero: "variable", trad: "muchos" },
  { lema: "multus", tipo: "adjetivo", raiz: "mult-", decl: "1.ª y 2.ª", genero: "variable", trad: "mucho" },
  { lema: "nātālis", tipo: "adjetivo", raiz: "natal-", decl: "3.ª", genero: "variable", trad: "natal" },
  { lema: "nōbilis", tipo: "adjetivo", raiz: "nobil-", decl: "3.ª", genero: "variable", trad: "noble" },
  { lema: "noster", tipo: "adjetivo", raiz: "nostr-", decl: "1.ª y 2.ª", genero: "variable", trad: "nuestro" },
  { lema: "nōtissimus", tipo: "adjetivo", raiz: "notissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy famoso" },
  { lema: "novus", tipo: "adjetivo", raiz: "nov-", decl: "1.ª y 2.ª", genero: "variable", trad: "nuevo" },
  { lema: "nūllus", tipo: "adjetivo", raiz: "null-", decl: "1.ª y 2.ª (Irreg.)", genero: "variable", trad: "ninguno" },
  { lema: "occupātus", tipo: "adjetivo", raiz: "occupat-", decl: "1.ª y 2.ª", genero: "variable", trad: "ocupado" },
  { lema: "omnis", tipo: "adjetivo", raiz: "omn-", decl: "3.ª", genero: "variable", trad: "todo" },
  { lema: "optimus", tipo: "adjetivo", raiz: "optim-", decl: "1.ª y 2.ª", genero: "variable", trad: "óptimo" },
  { lema: "ōtiōsus", tipo: "adjetivo", raiz: "otios-", decl: "1.ª y 2.ª", genero: "variable", trad: "ocioso" },
  { lema: "parātus", tipo: "adjetivo", raiz: "parat-", decl: "1.ª y 2.ª", genero: "variable", trad: "preparado" },
  { lema: "parvus", tipo: "adjetivo", raiz: "parv-", decl: "1.ª y 2.ª", genero: "variable", trad: "pequeño" },
  { lema: "pauperrimus", tipo: "adjetivo", raiz: "pauperrim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy pobre" },
  { lema: "perīculōsus", tipo: "adjetivo", raiz: "periculos-", decl: "1.ª y 2.ª", genero: "variable", trad: "peligroso" },
  { lema: "personātus", tipo: "adjetivo", raiz: "personat-", decl: "1.ª y 2.ª", genero: "variable", trad: "enmascarado" },
  { lema: "perterritus", tipo: "adjetivo", raiz: "perterrit-", decl: "1.ª y 2.ª", genero: "variable", trad: "aterrorizado" },
  { lema: "pessimus", tipo: "adjetivo", raiz: "pessim-", decl: "1.ª y 2.ª", genero: "variable", trad: "pésimo" },
  { lema: "plēnus", tipo: "adjetivo", raiz: "plen-", decl: "1.ª y 2.ª", genero: "variable", trad: "lleno" },
  { lema: "plūrimus", tipo: "adjetivo", raiz: "plurim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muchísimos" },
  { lema: "Pompēiānus", tipo: "adjetivo", raiz: "Pompeian-", decl: "1.ª y 2.ª", genero: "variable", trad: "pompeyano" },
  { lema: "pretiōsus", tipo: "adjetivo", raiz: "pretios-", decl: "1.ª y 2.ª", genero: "variable", trad: "precioso" },
  { lema: "prīmus", tipo: "adjetivo", raiz: "prim-", decl: "1.ª y 2.ª", genero: "variable", trad: "primero" },
  { lema: "probus", tipo: "adjetivo", raiz: "prob-", decl: "1.ª y 2.ª", genero: "variable", trad: "honesto" },
  { lema: "proximus", tipo: "adjetivo", raiz: "proxim-", decl: "1.ª y 2.ª", genero: "variable", trad: "próximo" },
  { lema: "pulcher", tipo: "adjetivo", raiz: "pulchr-", decl: "1.ª y 2.ª", genero: "variable", trad: "hermoso" },
  { lema: "pulcherrimus", tipo: "adjetivo", raiz: "pulcherrim-", decl: "1.ª y 2.ª", genero: "variable", trad: "hermosísimo" },
  { lema: "quadrāgintā", tipo: "adjetivo", raiz: "quadraginta", decl: "Indeclinable", genero: "variable", trad: "cuarenta" },
  { lema: "quantī?", tipo: "adjetivo", raiz: "quant-", decl: "1.ª y 2.ª", genero: "variable", trad: "¿cuánto?" },
  { lema: "quiētus", tipo: "adjetivo", raiz: "quiet-", decl: "1.ª y 2.ª", genero: "variable", trad: "tranquilo" },
  { lema: "quīndecim", tipo: "adjetivo", raiz: "quindecim", decl: "Indeclinable", genero: "variable", trad: "quince" },
  { lema: "quīnquāgintā", tipo: "adjetivo", raiz: "quinquaginta", decl: "Indeclinable", genero: "variable", trad: "cincuenta" },
  { lema: "quīnque", tipo: "adjetivo", raiz: "quinque", decl: "Indeclinable", genero: "variable", trad: "cinco" },
  { lema: "rīdiculus", tipo: "adjetivo", raiz: "ridicul-", decl: "1.ª y 2.ª", genero: "variable", trad: "ridículo" },
  { lema: "Rōmānus", tipo: "adjetivo", raiz: "Rōmān-", decl: "1.ª y 2.ª", genero: "variable", trad: "romano" },
  { lema: "scissus", tipo: "adjetivo", raiz: "sciss-", decl: "1.ª y 2.ª", genero: "variable", trad: "rasgado" },
  { lema: "scurrīlis", tipo: "adjetivo", raiz: "scurril-", decl: "3.ª", genero: "variable", trad: "vulgar" },
  { lema: "secundus", tipo: "adjetivo", raiz: "secund-", decl: "1.ª y 2.ª", genero: "variable", trad: "segundo" },
  { lema: "sēmirutus", tipo: "adjetivo", raiz: "semirut-", decl: "1.ª y 2.ª", genero: "variable", trad: "medio derruido" },
  { lema: "sēmisomnus", tipo: "adjetivo", raiz: "semisomn-", decl: "1.ª y 2.ª", genero: "variable", trad: "medio dormido" },
  { lema: "senior", tipo: "adjetivo", raiz: "senior-", decl: "3.ª (Comp.)", genero: "variable", trad: "más viejo" },
  { lema: "sollicitus", tipo: "adjetivo", raiz: "sollicit-", decl: "1.ª y 2.ª", genero: "variable", trad: "preocupado" },
  { lema: "sōlus", tipo: "adjetivo", raiz: "sol-", decl: "1.ª y 2.ª (Irreg.)", genero: "variable", trad: "solo" },
  { lema: "sordidus", tipo: "adjetivo", raiz: "sordid-", decl: "1.ª y 2.ª", genero: "variable", trad: "sucio" },
  { lema: "splendidus", tipo: "adjetivo", raiz: "splendid-", decl: "1.ª y 2.ª", genero: "variable", trad: "espléndido" },
  { lema: "stultissimus", tipo: "adjetivo", raiz: "stultissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy tonto" },
  { lema: "suus", tipo: "adjetivo", raiz: "su-", decl: "1.ª y 2.ª", genero: "variable", trad: "suyo" },
  { lema: "tertius", tipo: "adjetivo", raiz: "terti-", decl: "1.ª y 2.ª", genero: "variable", trad: "tercero" },
  { lema: "tōtus", tipo: "adjetivo", raiz: "tot-", decl: "1.ª y 2.ª (Irreg.)", genero: "variable", trad: "todo" },
  { lema: "trēs", tipo: "adjetivo", raiz: "tri-", decl: "3.ª", genero: "variable", trad: "tres" },
  { lema: "trīgintā", tipo: "adjetivo", raiz: "triginta", decl: "Indeclinable", genero: "variable", trad: "treinta" },
  { lema: "trīstis", tipo: "adjetivo", raiz: "trist-", decl: "3.ª", genero: "variable", trad: "triste" },
  { lema: "turbulentus", tipo: "adjetivo", raiz: "turbulent-", decl: "1.ª y 2.ª", genero: "variable", trad: "turbulento" },
  { lema: "tūtus", tipo: "adjetivo", raiz: "tut-", decl: "1.ª y 2.ª", genero: "variable", trad: "seguro" },
  { lema: "tuus", tipo: "adjetivo", raiz: "tu-", decl: "1.ª y 2.ª", genero: "variable", trad: "tuyo" },
  { lema: "ūnus", tipo: "adjetivo", raiz: "un-", decl: "1.ª y 2.ª (Irreg.)", genero: "variable", trad: "uno" },
  { lema: "ūtilissimus", tipo: "adjetivo", raiz: "utilissim-", decl: "1.ª y 2.ª", genero: "variable", trad: "muy útil" },
  { lema: "vērus", tipo: "adjetivo", raiz: "ver-", decl: "1.ª y 2.ª", genero: "variable", trad: "verdadero" },
  { lema: "vīgintī", tipo: "adjetivo", raiz: "viginti", decl: "Indeclinable", genero: "variable", trad: "veinte" }
];