
const adverbios = [
  { lema: "audācissimē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "muy audazmente" },
  { lema: "cautē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "con cautela" },
  { lema: "celeriter", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "rápidamente" },
  { lema: "celerrimē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "muy rápidamente" },
  { lema: "cotīdiē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "diariamente" },
  { lema: "cūr?", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "¿por qué?" },
  { lema: "deinde", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "luego" },
  { lema: "dīligenter", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "diligentemente" },
  { lema: "diū", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "por mucho tiempo" },
  { lema: "facile", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "fácilmente" },
  { lema: "ferōciter", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "ferozmente" },
  { lema: "fortasse", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "quizás" },
  { lema: "fortiter", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "valientemente" },
  { lema: "frūstrā", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "en vano" },
  { lema: "graviter", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "gravemente" },
  { lema: "heri", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "ayer" },
  { lema: "hodiē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "hoy" },
  { lema: "hūc", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "acá" },
  { lema: "iam", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "ya" },
  { lema: "iamprīdem", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "hace mucho tiempo" },
  { lema: "ibi", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "allí" },
  { lema: "igitur", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "por lo tanto" },
  { lema: "impūne", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "impunemente" },
  { lema: "intentē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "atentamente" },
  { lema: "intus", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "dentro" },
  { lema: "ita", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "así" },
  { lema: "iterum", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "de nuevo" },
  { lema: "laetē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "alegremente" },
  { lema: "longē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "lejos" },
  { lema: "magnificē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "magníficamente" },
  { lema: "māne", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "por la mañana" },
  { lema: "minimē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "de ninguna manera" },
  { lema: "mox", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "pronto" },
  { lema: "nimium", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "demasiado" },
  { lema: "nōn", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "no" },
  { lema: "num?", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "¿acaso...?" },
  { lema: "numquam", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "nunca" },
  { lema: "nunc", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "ahora" },
  { lema: "ōlim", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "antaño" },
  { lema: "optimē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "muy bien" },
  { lema: "paene", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "casi" },
  { lema: "paulīsper", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "por poco tiempo" },
  { lema: "posteā", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "después" },
  { lema: "postrēmō", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "finalmente" },
  { lema: "postrīdiē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "al día siguiente" },
  { lema: "quam", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "que / cuán" },
  { lema: "quō?", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "¿a dónde?" },
  { lema: "saepe", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "a menudo" },
  { lema: "semper", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "siempre" },
  { lema: "sēnsim", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "gradualmente" },
  { lema: "statim", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "al instante" },
  { lema: "suāviter", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "dulcemente" },
  { lema: "subitō", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "de repente" },
  { lema: "tacitē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "en silencio" },
  { lema: "tandem", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "por fin" },
  { lema: "tantum", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "solamente" },
  { lema: "timidē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "tímidamente" },
  { lema: "tum", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "entonces" },
  { lema: "ubi", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "dónde" },
  { lema: "ubīque", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "en todas partes" },
  { lema: "valdē", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "muy" },
  { lema: "vehementer", tipo: "adverbio", raiz: "-", decl: "Invariable", trad: "vehementemente" }
];