const pronombres = [
  // --- pde (Demostrativos) ---
  { lema: "hāc", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "esta (abl)" },
  { lema: "hae", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "estas" },
  { lema: "haec", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "esta / estas / esto" },
  { lema: "hanc", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "a esta" },
  { lema: "hārum", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "de estas" },
  { lema: "hās", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "a estas" },
  { lema: "hī", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "estos" },
  { lema: "hic", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "este" },
  { lema: "hīs", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "para estos/as" },
  { lema: "hoc", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "esto / este (acus/abl)" },
  { lema: "hōc", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "con este / con esto" },
  { lema: "hōrum", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "de estos" },
  { lema: "hōs", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "a estos" },
  { lema: "huic", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "para este/a" },
  { lema: "huīus", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "de este/a" },
  { lema: "hunc", tipo: "pronombre", raiz: "hic", decl: "pde", trad: "a este" },
  { lema: "illa", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "aquella / ella" },
  { lema: "illā", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "con aquella" },
  { lema: "illae", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "aquellas" },
  { lema: "illam", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "a aquella" },
  { lema: "illārum", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "de aquellas" },
  { lema: "illās", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "a aquellas" },
  { lema: "ille", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "aquel / él" },
  { lema: "illī", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "para aquel / aquellos" },
  { lema: "illīs", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "para aquellos/as" },
  { lema: "illīus", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "de aquel" },
  { lema: "illō", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "con aquel" },
  { lema: "illōrum", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "de aquellos" },
  { lema: "illōs", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "a aquellos" },
  { lema: "illud", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "aquello / ello" },
  { lema: "illum", tipo: "pronombre", raiz: "ille", decl: "pde", trad: "a aquel" },
  { lema: "ista", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "esa" },
  { lema: "istā", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "con esa" },
  { lema: "istae", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "esas" },
  { lema: "istam", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "a esa" },
  { lema: "istārum", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "de esas" },
  { lema: "istās", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "a esas" },
  { lema: "iste", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "ese" },
  { lema: "isti", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "esos" },
  { lema: "istī", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "para ese / esos" },
  { lema: "istīs", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "para esos/as" },
  { lema: "istīus", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "de ese" },
  { lema: "istō", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "con ese" },
  { lema: "istōrum", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "de esos" },
  { lema: "istōs", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "a esos" },
  { lema: "istud", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "eso" },
  { lema: "istum", tipo: "pronombre", raiz: "iste", decl: "pde", trad: "a ese" },

  // --- pen (Enfático - Ipse) ---
  { lema: "ipsa", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "ella misma" },
  { lema: "ipsā", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "con ella misma" },
  { lema: "ipsae", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "ellas mismas" },
  { lema: "ipsam", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "a ella misma" },
  { lema: "ipsārum", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "de ellas mismas" },
  { lema: "ipsās", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "a ellas mismas" },
  { lema: "ipse", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "él mismo" },
  { lema: "ipsī", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "ellos mismos / para él mismo" },
  { lema: "ipsīs", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "para ellos mismos" },
  { lema: "ipsīus", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "de él mismo" },
  { lema: "ipsō", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "con él mismo" },
  { lema: "ipsōrum", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "de ellos mismos" },
  { lema: "ipsōs", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "a ellos mismos" },
  { lema: "ipsum", tipo: "pronombre", raiz: "ipse", decl: "pen", trad: "mismo (neutro) / a él mismo" },

  // --- pfe (Identidad - Idem) ---
  { lema: "eadem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "la misma" },
  { lema: "eādem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "con la misma" },
  { lema: "eandem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "a la misma" },
  { lema: "eārundem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "de las mismas" },
  { lema: "eāsdem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "a las mismas" },
  { lema: "eaede", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "las mismas" },
  { lema: "eīdem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "el mismo / los mismos" },
  { lema: "eiīsdem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "a los mismos" },
  { lema: "eīsdem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "a los mismos" },
  { lema: "eiusdem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "del mismo" },
  { lema: "eōdem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "con lo mismo / al mismo lugar" },
  { lema: "eōrundem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "de los mismos" },
  { lema: "eōsdem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "a los mismos" },
  { lema: "eundem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "al mismo" },
  { lema: "īdem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "el mismo" },
  { lema: "iidem", tipo: "pronombre", raiz: "idem", decl: "pfe", trad: "los mismos" },

  // --- pfo (Fórico - Is) ---
  { lema: "ea", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "ella / la" },
  { lema: "eā", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "con ella" },
  { lema: "eae", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "ellas" },
  { lema: "eam", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "a ella / la" },
  { lema: "eārum", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "de ellas" },
  { lema: "eās", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "a ellas / las" },
  { lema: "eī", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "para él/ella / ellos" },
  { lema: "eiī", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "ellos" },
  { lema: "eiīs", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "para ellos/as" },
  { lema: "eīs", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "para ellos/as" },
  { lema: "eīus", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "de él/ella" },
  { lema: "eō", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "con él" },
  { lema: "eōrum", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "de ellos" },
  { lema: "eōs", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "a ellos / los" },
  { lema: "eum", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "a él / lo" },
  { lema: "id", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "ello / lo" },
  { lema: "is", tipo: "pronombre", raiz: "is", decl: "pfo", trad: "él / este" },

  // --- pii (Interrogativo) ---
  { lema: "quid", tipo: "pronombre", raiz: "quis", decl: "pii", trad: "qué (acus/nom neutro)" },
  { lema: "quis", tipo: "pronombre", raiz: "quis", decl: "pii", trad: "quién" },

  // --- pir (Irregulares) ---
  { lema: "ego", tipo: "pronombre", raiz: "ego", decl: "pir", trad: "yo" },
  { lema: "mēcum", tipo: "pronombre", raiz: "ego", decl: "pir", trad: "conmigo" },
  { lema: "nemo", tipo: "pronombre", raiz: "nemo", decl: "pir", trad: "nadie" },
  { lema: "nōs", tipo: "pronombre", raiz: "nos", decl: "pir", trad: "nosotros (nom/acus)" },
  { lema: "qui", tipo: "pronombre", raiz: "qui", decl: "pir", trad: "quien / el que" },
  { lema: "quid?", tipo: "pronombre", raiz: "quis", decl: "pir", trad: "¿qué?" },
  { lema: "quis?", tipo: "pronombre", raiz: "quis", decl: "pir", trad: "¿quién?" },
  { lema: "tū", tipo: "pronombre", raiz: "tu", decl: "pir", trad: "tú" },
  { lema: "vōbīs", tipo: "pronombre", raiz: "vos", decl: "pir", trad: "os / para vosotros" },
  { lema: "vos", tipo: "pronombre", raiz: "vos", decl: "pir", trad: "vosotros" },

  // --- poi (Indefinidos y otros) ---
  { lema: "alia", tipo: "pronombre", raiz: "alius", decl: "poi", trad: "otra" },
  { lema: "aliqua", tipo: "pronombre", raiz: "aliquis", decl: "poi", trad: "alguna" },
  { lema: "aliquid", tipo: "pronombre", raiz: "aliquis", decl: "poi", trad: "algo" },
  { lema: "aliquis", tipo: "pronombre", raiz: "aliquis", decl: "poi", trad: "alguien" },
  { lema: "aliquod", tipo: "pronombre", raiz: "aliquis", decl: "poi", trad: "alguno (adj)" },
  { lema: "aliud", tipo: "pronombre", raiz: "alius", decl: "poi", trad: "otro (neutro)" },
  { lema: "alius", tipo: "pronombre", raiz: "alius", decl: "poi", trad: "otro" },
  { lema: "alter", tipo: "pronombre", raiz: "alter", decl: "poi", trad: "el otro (de dos)" },
  { lema: "altera", tipo: "pronombre", raiz: "alter", decl: "poi", trad: "la otra (de dos)" },
  { lema: "alterum", tipo: "pronombre", raiz: "alter", decl: "poi", trad: "lo otro (de dos)" },
  { lema: "nēmō", tipo: "pronombre", raiz: "nemo", decl: "poi", trad: "nadie" },
  { lema: "neuter", tipo: "pronombre", raiz: "neuter", decl: "poi", trad: "ninguno (de dos)" },
  { lema: "neutra", tipo: "pronombre", raiz: "neuter", decl: "poi", trad: "ninguna (de dos)" },
  { lema: "neutrum", tipo: "pronombre", raiz: "neuter", decl: "poi", trad: "ninguno (de dos)" },
  { lema: "nihil", tipo: "pronombre", raiz: "nihil", decl: "poi", trad: "nada" },
  { lema: "nūlla", tipo: "pronombre", raiz: "nullus", decl: "poi", trad: "ninguna" },
  { lema: "nūllum", tipo: "pronombre", raiz: "nullus", decl: "poi", trad: "ninguno" },
  { lema: "nūllus", tipo: "pronombre", raiz: "nullus", decl: "poi", trad: "ninguno" },
  { lema: "quaedam", tipo: "pronombre", raiz: "quidam", decl: "poi", trad: "cierta / alguna" },
  { lema: "quaelibet", tipo: "pronombre", raiz: "quilibet", decl: "poi", trad: "cualquiera (fem)" },
  { lema: "quaeque", tipo: "pronombre", raiz: "quisque", decl: "poi", trad: "cada una" },
  { lema: "quaevīs", tipo: "pronombre", raiz: "quivis", decl: "poi", trad: "cualquiera (fem)" },
  { lema: "quicquam", tipo: "pronombre", raiz: "quisquam", decl: "poi", trad: "algo (en negación)" },
  { lema: "quīdam", tipo: "pronombre", raiz: "quidam", decl: "poi", trad: "cierto / uno" },
  { lema: "quiddam", tipo: "pronombre", raiz: "quidam", decl: "poi", trad: "algo cierto" },
  { lema: "quidlibet", tipo: "pronombre", raiz: "quilibet", decl: "poi", trad: "cualquier cosa" },
  { lema: "quidquam", tipo: "pronombre", raiz: "quisquam", decl: "poi", trad: "algo (en negación)" },
  { lema: "quidque", tipo: "pronombre", raiz: "quisque", decl: "poi", trad: "cada cosa" },
  { lema: "quidvīs", tipo: "pronombre", raiz: "quivis", decl: "poi", trad: "cualquier cosa" },
  { lema: "quīlibet", tipo: "pronombre", raiz: "quilibet", decl: "poi", trad: "cualquiera" },
  { lema: "quisquam", tipo: "pronombre", raiz: "quisquam", decl: "poi", trad: "alguien (en negación)" },
  { lema: "quisque", tipo: "pronombre", raiz: "quisque", decl: "poi", trad: "cada uno" },
  { lema: "quīvīs", tipo: "pronombre", raiz: "quivis", decl: "poi", trad: "cualquiera" },
  { lema: "quoddam", tipo: "pronombre", raiz: "quidam", decl: "poi", trad: "cierto (neutro)" },
  { lema: "quodlibet", tipo: "pronombre", raiz: "quilibet", decl: "poi", trad: "cualquiera (neutro)" },
  { lema: "quodque", tipo: "pronombre", raiz: "quisque", decl: "poi", trad: "cada uno (neutro)" },
  { lema: "quodvīs", tipo: "pronombre", raiz: "quivis", decl: "poi", trad: "cualquiera (neutro)" },
  { lema: "sōla", tipo: "pronombre", raiz: "solus", decl: "poi", trad: "sola" },
  { lema: "sōlum", tipo: "pronombre", raiz: "solus", decl: "poi", trad: "solo / solamente" },
  { lema: "sōlus", tipo: "pronombre", raiz: "solus", decl: "poi", trad: "solo" },
  { lema: "tōta", tipo: "pronombre", raiz: "totus", decl: "poi", trad: "toda" },
  { lema: "tōtum", tipo: "pronombre", raiz: "totus", decl: "poi", trad: "todo" },
  { lema: "tōtus", tipo: "pronombre", raiz: "totus", decl: "poi", trad: "todo" },
  { lema: "ūlla", tipo: "pronombre", raiz: "ullus", decl: "poi", trad: "alguna" },
  { lema: "ūllum", tipo: "pronombre", raiz: "ullus", decl: "poi", trad: "alguno" },
  { lema: "ūllus", tipo: "pronombre", raiz: "ullus", decl: "poi", trad: "alguno" },
  { lema: "uterque", tipo: "pronombre", raiz: "uterque", decl: "poi", trad: "ambos / cada uno de dos" },
  { lema: "utraque", tipo: "pronombre", raiz: "uterque", decl: "poi", trad: "ambas" },
  { lema: "utrumque", tipo: "pronombre", raiz: "uterque", decl: "poi", trad: "ambos (neutro)" },

  // --- ppe (Personales) ---
  { lema: "meī", tipo: "pronombre", raiz: "ego", decl: "ppe", trad: "de mí" },
  { lema: "mē", tipo: "pronombre", raiz: "ego", decl: "ppe", trad: "me / a mí" },
  { lema: "mihi", tipo: "pronombre", raiz: "ego", decl: "ppe", trad: "me / para mí" },
  { lema: "nōbīs", tipo: "pronombre", raiz: "nos", decl: "ppe", trad: "nos / para nosotros" },
  { lema: "nōbīscum", tipo: "pronombre", raiz: "nos", decl: "ppe", trad: "con nosotros" },
  { lema: "nōs", tipo: "pronombre", raiz: "nos", decl: "ppe", trad: "nosotros (acusativo)" },
  { lema: "nostrī", tipo: "pronombre", raiz: "nos", decl: "ppe", trad: "de nosotros" },
  { lema: "sē", tipo: "pronombre", raiz: "sui", decl: "ppe", trad: "se / a sí mismo" },
  { lema: "sēcum", tipo: "pronombre", raiz: "sui", decl: "ppe", trad: "consigo mismo" },
  { lema: "sibi", tipo: "pronombre", raiz: "sui", decl: "ppe", trad: "se / para sí" },
  { lema: "suī", tipo: "pronombre", raiz: "sui", decl: "ppe", trad: "de sí mismo" },
  { lema: "tē", tipo: "pronombre", raiz: "tu", decl: "ppe", trad: "te / a ti" },
  { lema: "tēcum", tipo: "pronombre", raiz: "tu", decl: "ppe", trad: "contigo" },
  { lema: "tibi", tipo: "pronombre", raiz: "tu", decl: "ppe", trad: "te / para ti" },
  { lema: "tu", tipo: "pronombre", raiz: "tu", decl: "ppe", trad: "tú (vocativo/nom)" },
  { lema: "tuī", tipo: "pronombre", raiz: "tu", decl: "ppe", trad: "de ti" },
  { lema: "uōbīs", tipo: "pronombre", raiz: "vos", decl: "ppe", trad: "os / para vosotros" },
  { lema: "uōbīscum", tipo: "pronombre", raiz: "vos", decl: "ppe", trad: "con vosotros" },
  { lema: "uōs", tipo: "pronombre", raiz: "vos", decl: "ppe", trad: "os / a vosotros" },
  { lema: "uestrī", tipo: "pronombre", raiz: "vester", decl: "ppe", trad: "de vosotros" },

  // --- ppo (Posesivos) ---
  { lema: "mea", tipo: "pronombre", raiz: "meus", decl: "ppo", trad: "mía" },
  { lema: "meum", tipo: "pronombre", raiz: "meus", decl: "ppo", trad: "mío (neutro)" },
  { lema: "meus", tipo: "pronombre", raiz: "meus", decl: "ppo", trad: "mío" },
  { lema: "noster", tipo: "pronombre", raiz: "noster", decl: "ppo", trad: "nuestro" },
  { lema: "nostra", tipo: "pronombre", raiz: "noster", decl: "ppo", trad: "nuestra" },
  { lema: "nostrum", tipo: "pronombre", raiz: "noster", decl: "ppo", trad: "nuestro (neutro)" },
  { lema: "sua", tipo: "pronombre", raiz: "suus", decl: "ppo", trad: "suya" },
  { lema: "suum", tipo: "pronombre", raiz: "suus", decl: "ppo", trad: "suyo (neutro)" },
  { lema: "suus", tipo: "pronombre", raiz: "suus", decl: "ppo", trad: "suyo" },
  { lema: "tua", tipo: "pronombre", raiz: "tuus", decl: "ppo", trad: "tuya" },
  { lema: "tuum", tipo: "pronombre", raiz: "tuus", decl: "ppo", trad: "tuyo (neutro)" },
  { lema: "tuus", tipo: "pronombre", raiz: "tuus", decl: "ppo", trad: "tuyo" },
  { lema: "uester", tipo: "pronombre", raiz: "vester", decl: "ppo", trad: "vuestro" },
  { lema: "uestra", tipo: "pronombre", raiz: "vester", decl: "ppo", trad: "vuestra" },
  { lema: "uestrum", tipo: "pronombre", raiz: "vester", decl: "ppo", trad: "vuestro (neutro)" },

  // --- ppr (Pronominales) ---
  { lema: "ipsa", tipo: "pronombre", raiz: "ipse", decl: "ppr", trad: "misma" },
  { lema: "ipse", tipo: "pronombre", raiz: "ipse", decl: "ppr", trad: "mismo" },
  { lema: "quidam", tipo: "pronombre", raiz: "quidam", decl: "ppr", trad: "cierto / alguno" },
  { lema: "ullus", tipo: "pronombre", raiz: "ullus", decl: "ppr", trad: "alguno" },
  { lema: "uter", tipo: "pronombre", raiz: "uter", decl: "ppr", trad: "¿cuál de los dos?" },
  { lema: "utra", tipo: "pronombre", raiz: "uter", decl: "ppr", trad: "¿cuál de las dos?" },
  { lema: "utrum", tipo: "pronombre", raiz: "uter", decl: "ppr", trad: "¿cuál de los dos (n)?" },
  { lema: "vester", tipo: "pronombre", raiz: "vester", decl: "ppr", trad: "vuestro" },
  { lema: "vestra", tipo: "pronombre", raiz: "vester", decl: "ppr", trad: "vuestra" },
  { lema: "vestrum", tipo: "pronombre", raiz: "vester", decl: "ppr", trad: "vuestro (n)" },

  // --- pre (Relativos) ---
  { lema: "cui", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "al cual / a quien" },
  { lema: "cuius", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "del cual / de quien" },
  { lema: "quā", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "por la cual / por donde" },
  { lema: "quae", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "la que / las cuales" },
  { lema: "quam", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "a la cual / a quien" },
  { lema: "quārum", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "de las cuales" },
  { lema: "quās", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "a las cuales" },
  { lema: "quem", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "al cual / a quien" },
  { lema: "quī", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "los cuales" },
  { lema: "quibus", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "para los cuales / con los cuales" },
  { lema: "quō", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "por el cual / adonde" },
  { lema: "quod", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "lo cual / lo que" },
  { lema: "quōrum", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "de los cuales" },
  { lema: "quōs", tipo: "pronombre", raiz: "qui", decl: "pre", trad: "a los cuales" }
];