const sustantivos = [
  // BLOQUE 1
  { lema: "Actius", tipo: "sustantivo", raiz: "Acti-", decl: "2.ª", genero: "m", trad: "Actius" },
  { lema: "āctor", tipo: "sustantivo", raiz: "actor-", decl: "3.ª", genero: "m", trad: "actor" },
  { lema: "Āfer", tipo: "sustantivo", raiz: "Afr-", decl: "2.ª", genero: "m", trad: "Afer (El Africano)" },
  { lema: "agricola", tipo: "sustantivo", raiz: "agricol-", decl: "1.ª", genero: "m", trad: "agricultor" }, // Nota: Masc de 1.ª
  { lema: "ager", tipo: "sustantivo", raiz: "agr-", decl: "2.ª", genero: "m", trad: "campo" }, // Nota: Masc de 1.ª
  { lema: "Alexander", tipo: "sustantivo", raiz: "Alexandr-", decl: "2.ª", genero: "m", trad: "Alejandro" },
  { lema: "amīca", tipo: "sustantivo", raiz: "amic-", decl: "1.ª", genero: "f", trad: "amiga" },
  { lema: "amīcus", tipo: "sustantivo", raiz: "amic-", decl: "2.ª", genero: "m", trad: "amigo" },
  { lema: "amphitheātrum", tipo: "sustantivo", raiz: "amphitheatr-", decl: "2.ª", genero: "n", trad: "anfiteatro" },
  { lema: "ancilla", tipo: "sustantivo", raiz: "ancill-", decl: "1.ª", genero: "f", trad: "esclava, sirvienta" },
  { lema: "Androclus", tipo: "sustantivo", raiz: "Androcl-", decl: "2.ª", genero: "m", trad: "Androclo" },
  { lema: "Anthrāx", tipo: "sustantivo", raiz: "Anthrac-", decl: "3.ª", genero: "m", trad: "Ántrax" },
  { lema: "ānulus", tipo: "sustantivo", raiz: "anul-", decl: "2.ª", genero: "m", trad: "anillo" },
  { lema: "aper", tipo: "sustantivo", raiz: "apr-", decl: "2.ª", genero: "m", trad: "jabalí" },
  { lema: "apodytērium", tipo: "sustantivo", raiz: "apodyteri-", decl: "2.ª", genero: "n", trad: "vestuario" },
  { lema: "architectus", tipo: "sustantivo", raiz: "architect-", decl: "2.ª", genero: "m", trad: "arquitecto" },
  { lema: "arēna", tipo: "sustantivo", raiz: "aren-", decl: "1.ª", genero: "f", trad: "arena" },
  { lema: "argentāria", tipo: "sustantivo", raiz: "argentari-", decl: "1.ª", genero: "f", trad: "banco" },
  { lema: "argentārius", tipo: "sustantivo", raiz: "argentari-", decl: "2.ª", genero: "m", trad: "banquero" },
  { lema: "argūmentum", tipo: "sustantivo", raiz: "argument-", decl: "2.ª", genero: "n", trad: "prueba, evidencia" },
  { lema: "artifex", tipo: "sustantivo", raiz: "artific-", decl: "3.ª", genero: "m", trad: "artista, artesano" },
  { lema: "asinus", tipo: "sustantivo", raiz: "asin-", decl: "2.ª", genero: "m", trad: "asno, burro" },
  { lema: "āthlēta", tipo: "sustantivo", raiz: "athlet-", decl: "1.ª", genero: "m", trad: "atleta" }, // Nota: Masc de 1.ª
  { lema: "ātrium", tipo: "sustantivo", raiz: "atri-", decl: "2.ª", genero: "n", trad: "atrio" },
  { lema: "auctor", tipo: "sustantivo", raiz: "auctor-", decl: "3.ª", genero: "m", trad: "creador, autor" },
  { lema: "aurae", tipo: "sustantivo", raiz: "aur-", decl: "1.ª", genero: "f", trad: "aire, brisa" },
  { lema: "auxilium", tipo: "sustantivo", raiz: "auxili-", decl: "2.ª", genero: "n", trad: "ayuda" },
  { lema: "avārus", tipo: "sustantivo", raiz: "avar-", decl: "2.ª", genero: "m", trad: "avaro" },
  { lema: "barba", tipo: "sustantivo", raiz: "barb-", decl: "1.ª", genero: "f", trad: "barba" },
  { lema: "barbarus", tipo: "sustantivo", raiz: "barbar-", decl: "2.ª", genero: "m", trad: "extranjero, bárbaro" },
  { lema: "Barbillus", tipo: "sustantivo", raiz: "Barbill-", decl: "2.ª", genero: "m", trad: "Barbilo" },
  { lema: "basilica", tipo: "sustantivo", raiz: "basilic-", decl: "1.ª", genero: "f", trad: "basílica" },
  { lema: "bēstia", tipo: "sustantivo", raiz: "besti-", decl: "1.ª", genero: "f", trad: "bestia" },
  { lema: "bēstiārius", tipo: "sustantivo", raiz: "bestiari-", decl: "2.ª", genero: "m", trad: "bestiario" },
  { lema: "Caecilius", tipo: "sustantivo", raiz: "Caecili-", decl: "2.ª", genero: "m", trad: "Cecilio" },
  { lema: "caelum", tipo: "sustantivo", raiz: "cael-", decl: "2.ª", genero: "n", trad: "cielo" }, // A veces masc en plural, pero n en sg.
  { lema: "caldārium", tipo: "sustantivo", raiz: "caldari-", decl: "2.ª", genero: "n", trad: "caldarium" },
  { lema: "candidātus", tipo: "sustantivo", raiz: "candidat-", decl: "2.ª", genero: "m", trad: "candidato" },
  { lema: "canis", tipo: "sustantivo", raiz: "can-", decl: "3.ª", genero: "m", trad: "perro" }, // Puede ser f, ponemos m por defecto
  { lema: "caudex", tipo: "sustantivo", raiz: "caudic-", decl: "3.ª", genero: "m", trad: "idiota, tronco" },
  { lema: "caupō", tipo: "sustantivo", raiz: "caupon-", decl: "3.ª", genero: "m", trad: "posadero" },
  { lema: "cēna", tipo: "sustantivo", raiz: "cen-", decl: "1.ª", genero: "f", trad: "cena" },
  { lema: "centuriō", tipo: "sustantivo", raiz: "centurion-", decl: "3.ª", genero: "m", trad: "centurión" },
  { lema: "cēra", tipo: "sustantivo", raiz: "cer-", decl: "1.ª", genero: "f", trad: "cera" },
  { lema: "Cerberus", tipo: "sustantivo", raiz: "Cerber-", decl: "2.ª", genero: "m", trad: "Cerbero" },
  { lema: "cervus", tipo: "sustantivo", raiz: "cerv-", decl: "2.ª", genero: "m", trad: "ciervo" },
  { lema: "cibus", tipo: "sustantivo", raiz: "cib-", decl: "2.ª", genero: "m", trad: "comida" },
  { lema: "cinis", tipo: "sustantivo", raiz: "ciner-", decl: "3.ª", genero: "m", trad: "ceniza" },
  { lema: "cīvis", tipo: "sustantivo", raiz: "civ-", decl: "3.ª", genero: "m", trad: "ciudadano" },
  { lema: "clāmor", tipo: "sustantivo", raiz: "clamor-", decl: "3.ª", genero: "m", trad: "clamor" },
  { lema: "Clāra", tipo: "sustantivo", raiz: "Clar-", decl: "1.ª", genero: "f", trad: "Clara" },
  { lema: "Clēmēns", tipo: "sustantivo", raiz: "Clement-", decl: "3.ª", genero: "m", trad: "Clemente" },
  { lema: "columba", tipo: "sustantivo", raiz: "columb-", decl: "1.ª", genero: "f", trad: "paloma" },
  { lema: "cōnsilium", tipo: "sustantivo", raiz: "consili-", decl: "2.ª", genero: "n", trad: "plan, idea" },
  { lema: "contentiō", tipo: "sustantivo", raiz: "contention-", decl: "3.ª", genero: "f", trad: "disputa" },
  { lema: "contrōversia", tipo: "sustantivo", raiz: "controversi-", decl: "1.ª", genero: "f", trad: "debate" },
  { lema: "coquus", tipo: "sustantivo", raiz: "coqu-", decl: "2.ª", genero: "m", trad: "cocinero" },
  { lema: "Corvus", tipo: "sustantivo", raiz: "Corv-", decl: "2.ª", genero: "m", trad: "Corvo" },
  { lema: "crīnis", tipo: "sustantivo", raiz: "crin-", decl: "3.ª", genero: "m", trad: "cabello" },
  { lema: "cubiculum", tipo: "sustantivo", raiz: "cubicul-", decl: "2.ª", genero: "n", trad: "dormitorio" },
  { lema: "culīna", tipo: "sustantivo", raiz: "culin-", decl: "1.ª", genero: "f", trad: "cocina" },
  { lema: "dea", tipo: "sustantivo", raiz: "de-", decl: "1.ª", genero: "f", trad: "diosa" },
  { lema: "Decēns", tipo: "sustantivo", raiz: "Decent-", decl: "3.ª", genero: "m", trad: "Decente" },
  { lema: "dēliciae", tipo: "sustantivo", raiz: "delici-", decl: "1.ª", genero: "f", trad: "delicias" },
  { lema: "dēnārius", tipo: "sustantivo", raiz: "denari-", decl: "2.ª", genero: "m", trad: "denario" },
  { lema: "deus", tipo: "sustantivo", raiz: "de-", decl: "2.ª", genero: "m", trad: "dios" },
  { lema: "diēs", tipo: "sustantivo", raiz: "di-", decl: "5.ª", genero: "m", trad: "día" }, // Nota: 5ta masc
  { lema: "Diodōrus", tipo: "sustantivo", raiz: "Diodor-", decl: "2.ª", genero: "m", trad: "Diodoro" },
  { lema: "discus", tipo: "sustantivo", raiz: "disc-", decl: "2.ª", genero: "m", trad: "disco" },
  { lema: "dīvīsor", tipo: "sustantivo", raiz: "divisor-", decl: "3.ª", genero: "m", trad: "distribuidor" },
  { lema: "domina", tipo: "sustantivo", raiz: "domin-", decl: "1.ª", genero: "f", trad: "señora" },
  { lema: "dominus", tipo: "sustantivo", raiz: "domin-", decl: "2.ª", genero: "m", trad: "señor" },
  { lema: "dōnum", tipo: "sustantivo", raiz: "don-", decl: "2.ª", genero: "n", trad: "regalo" },
  { lema: "dubium", tipo: "sustantivo", raiz: "dubi-", decl: "2.ª", genero: "n", trad: "duda" },
  { lema: "epistula", tipo: "sustantivo", raiz: "epistul-", decl: "1.ª", genero: "f", trad: "carta" },
  { lema: "exanimātus", tipo: "sustantivo", raiz: "exanimat-", decl: "2.ª", genero: "m", trad: "inconsciente" }, // Usado como sustantivo aquí
  { lema: "fābula", tipo: "sustantivo", raiz: "fabul-", decl: "1.ª", genero: "f", trad: "historia" },
  { lema: "familia", tipo: "sustantivo", raiz: "famili-", decl: "1.ª", genero: "f", trad: "familia" },
  { lema: "fautor", tipo: "sustantivo", raiz: "fautor-", decl: "3.ª", genero: "m", trad: "partidario" },
  { lema: "fēlēs", tipo: "sustantivo", raiz: "fel-", decl: "3.ª", genero: "f", trad: "gato" },
  { lema: "Fēlīx", tipo: "sustantivo", raiz: "Felic-", decl: "3.ª", genero: "m", trad: "Félix" },
  { lema: "fēmina", tipo: "sustantivo", raiz: "femin-", decl: "1.ª", genero: "f", trad: "mujer" },
  { lema: "fīlia", tipo: "sustantivo", raiz: "fili-", decl: "1.ª", genero: "f", trad: "hija" },
  { lema: "fīlius", tipo: "sustantivo", raiz: "fili-", decl: "2.ª", genero: "m", trad: "hijo" },
  { lema: "fīnis", tipo: "sustantivo", raiz: "fin-", decl: "3.ª", genero: "m", trad: "fin, límite" },
  { lema: "flamma", tipo: "sustantivo", raiz: "flamm-", decl: "1.ª", genero: "f", trad: "llama" },
  { lema: "follis", tipo: "sustantivo", raiz: "foll-", decl: "3.ª", genero: "m", trad: "pelota" },
  { lema: "forum", tipo: "sustantivo", raiz: "for-", decl: "2.ª", genero: "n", trad: "foro" },
  { lema: "frāter", tipo: "sustantivo", raiz: "fratr-", decl: "3.ª", genero: "m", trad: "hermano" },
  { lema: "fugitīvus", tipo: "sustantivo", raiz: "fugitiv-", decl: "2.ª", genero: "m", trad: "fugitivo" },
  { lema: "fūmus", tipo: "sustantivo", raiz: "fum-", decl: "2.ª", genero: "m", trad: "humo" },
  { lema: "fūnambulus", tipo: "sustantivo", raiz: "funambul-", decl: "2.ª", genero: "m", trad: "funambulista" },
  { lema: "fundus", tipo: "sustantivo", raiz: "fund-", decl: "2.ª", genero: "m", trad: "granja" },
  { lema: "fūr", tipo: "sustantivo", raiz: "fur-", decl: "3.ª", genero: "m", trad: "ladrón" },
  { lema: "furcifer", tipo: "sustantivo", raiz: "furcifer-", decl: "2.ª", genero: "m", trad: "granuja" },
  { lema: "fūstis", tipo: "sustantivo", raiz: "fust-", decl: "3.ª", genero: "m", trad: "garrote" },
  { lema: "gladiātor", tipo: "sustantivo", raiz: "gladiator-", decl: "3.ª", genero: "m", trad: "gladiador" },
  { lema: "gladius", tipo: "sustantivo", raiz: "gladi-", decl: "2.ª", genero: "m", trad: "espada" },
  { lema: "Graecia", tipo: "sustantivo", raiz: "Graeci-", decl: "1.ª", genero: "f", trad: "Grecia" },

  // BLOQUE 2
  { lema: "grātiae", tipo: "sustantivo", raiz: "grati-", decl: "1.ª", genero: "f", trad: "gracias" },
  { lema: "Grumiō", tipo: "sustantivo", raiz: "Grumion-", decl: "3.ª", genero: "m", trad: "Grumio" },
  { lema: "Herculēs", tipo: "sustantivo", raiz: "Hercul-", decl: "3.ª", genero: "m", trad: "Hércules" },
  { lema: "Hermogenēs", tipo: "sustantivo", raiz: "Hermogen-", decl: "3.ª", genero: "m", trad: "Hermógenes" },
  { lema: "Holcōnius", tipo: "sustantivo", raiz: "Holconi-", decl: "2.ª", genero: "m", trad: "Holconio" },
  { lema: "homō", tipo: "sustantivo", raiz: "homin-", decl: "3.ª", genero: "m", trad: "hombre" },
  { lema: "hortus", tipo: "sustantivo", raiz: "hort-", decl: "2.ª", genero: "m", trad: "jardín" },
  { lema: "hospes", tipo: "sustantivo", raiz: "hospit-", decl: "3.ª", genero: "m", trad: "huésped" },
  { lema: "iānua", tipo: "sustantivo", raiz: "ianu-", decl: "1.ª", genero: "f", trad: "puerta" },
  { lema: "imitātor", tipo: "sustantivo", raiz: "imitator-", decl: "3.ª", genero: "m", trad: "imitador" },
  { lema: "imperium", tipo: "sustantivo", raiz: "imperi-", decl: "2.ª", genero: "n", trad: "imperio" },
  { lema: "incendium", tipo: "sustantivo", raiz: "incendi-", decl: "2.ª", genero: "n", trad: "incendio" },
  { lema: "īnfāns", tipo: "sustantivo", raiz: "infant-", decl: "3.ª", genero: "m", trad: "bebé" },
  { lema: "inimīcus", tipo: "sustantivo", raiz: "inimic-", decl: "2.ª", genero: "m", trad: "enemigo" },
  { lema: "īnscrīptiō", tipo: "sustantivo", raiz: "inscription-", decl: "3.ª", genero: "f", trad: "inscripción" },
  { lema: "īnsula", tipo: "sustantivo", raiz: "insul-", decl: "1.ª", genero: "f", trad: "isla" },
  { lema: "Īsis", tipo: "sustantivo", raiz: "Isid-", decl: "3.ª", genero: "f", trad: "Isis" },
  { lema: "iter", tipo: "sustantivo", raiz: "itiner-", decl: "3.ª", genero: "n", trad: "viaje" },
  { lema: "Iūcundus", tipo: "sustantivo", raiz: "Iucund-", decl: "2.ª", genero: "m", trad: "Jocundo" },
  { lema: "iūdex", tipo: "sustantivo", raiz: "iudic-", decl: "3.ª", genero: "m", trad: "juez" },
  { lema: "iuvenis", tipo: "sustantivo", raiz: "iuven-", decl: "3.ª", genero: "m", trad: "joven" },
  { lema: "larārium", tipo: "sustantivo", raiz: "larari-", decl: "2.ª", genero: "n", trad: "larario" },
  { lema: "larēs", tipo: "sustantivo", raiz: "lar-", decl: "3.ª", genero: "m", trad: "Lares" },
  { lema: "lectus", tipo: "sustantivo", raiz: "lect-", decl: "2.ª", genero: "m", trad: "lecho" },
  { lema: "leō", tipo: "sustantivo", raiz: "leon-", decl: "3.ª", genero: "m", trad: "león" },
  { lema: "liber", tipo: "sustantivo", raiz: "libr-", decl: "2.ª", genero: "m", trad: "libro" },
  { lema: "līberī", tipo: "sustantivo", raiz: "liber-", decl: "2.ª", genero: "m", trad: "hijos" },
  { lema: "līberta", tipo: "sustantivo", raiz: "libert-", decl: "1.ª", genero: "f", trad: "liberta" },
  { lema: "lībertās", tipo: "sustantivo", raiz: "libertat-", decl: "3.ª", genero: "f", trad: "libertad" },
  { lema: "lībertus", tipo: "sustantivo", raiz: "libert-", decl: "2.ª", genero: "m", trad: "liberto" },
  { lema: "lingua", tipo: "sustantivo", raiz: "lingu-", decl: "1.ª", genero: "f", trad: "lengua" },
  { lema: "Lūcia", tipo: "sustantivo", raiz: "Luci-", decl: "1.ª", genero: "f", trad: "Lucía" },
  { lema: "Lūcius", tipo: "sustantivo", raiz: "Luci-", decl: "2.ª", genero: "m", trad: "Lucio" },
  { lema: "Lucriō", tipo: "sustantivo", raiz: "Lucrion-", decl: "3.ª", genero: "m", trad: "Lucrión" },
  { lema: "lūna", tipo: "sustantivo", raiz: "lun-", decl: "1.ª", genero: "f", trad: "luna" },
  { lema: "lupus", tipo: "sustantivo", raiz: "lup-", decl: "2.ª", genero: "m", trad: "lobo" },
  { lema: "manus", tipo: "sustantivo", raiz: "man-", decl: "4.ª", genero: "f", trad: "mano" }, // Nota: 4ta Fem
  { lema: "Marcellus", tipo: "sustantivo", raiz: "Marcell-", decl: "2.ª", genero: "m", trad: "Marcelo" },
  { lema: "marītus", tipo: "sustantivo", raiz: "marit-", decl: "2.ª", genero: "m", trad: "marido" },
  { lema: "māter", tipo: "sustantivo", raiz: "matr-", decl: "3.ª", genero: "f", trad: "madre" },
  { lema: "mātrimōnium", tipo: "sustantivo", raiz: "matrimoni-", decl: "2.ª", genero: "n", trad: "matrimonio" },
  { lema: "Melissa", tipo: "sustantivo", raiz: "Meliss-", decl: "1.ª", genero: "f", trad: "Melisa" },
  { lema: "mendāx", tipo: "sustantivo", raiz: "mendac-", decl: "3.ª", genero: "m", trad: "mentiroso" },
  { lema: "mēnsa", tipo: "sustantivo", raiz: "mens-", decl: "1.ª", genero: "f", trad: "mesa" },
  { lema: "mercātor", tipo: "sustantivo", raiz: "mercator-", decl: "3.ª", genero: "m", trad: "mercader" },
  { lema: "Metella", tipo: "sustantivo", raiz: "Metell-", decl: "1.ª", genero: "f", trad: "Metela" },
  { lema: "Milō", tipo: "sustantivo", raiz: "Milon-", decl: "3.ª", genero: "m", trad: "Milón" },
  { lema: "missiō", tipo: "sustantivo", raiz: "mission-", decl: "3.ª", genero: "f", trad: "liberación" },
  { lema: "mōns", tipo: "sustantivo", raiz: "mont-", decl: "3.ª", genero: "m", trad: "montaña" },
  { lema: "mors", tipo: "sustantivo", raiz: "mort-", decl: "3.ª", genero: "f", trad: "muerte" },
  { lema: "murmillō", tipo: "sustantivo", raiz: "murmillon-", decl: "3.ª", genero: "m", trad: "mirmillón" },
  { lema: "mūrus", tipo: "sustantivo", raiz: "mur-", decl: "2.ª", genero: "m", trad: "muro" },
  { lema: "nāsus", tipo: "sustantivo", raiz: "nas-", decl: "2.ª", genero: "m", trad: "nariz" },
  { lema: "nauta", tipo: "sustantivo", raiz: "naut-", decl: "1.ª", genero: "m", trad: "marinero" }, // Masc de 1ra
  { lema: "nāvis", tipo: "sustantivo", raiz: "nav-", decl: "3.ª", genero: "f", trad: "nave, barco" },
  { lema: "negōtium", tipo: "sustantivo", raiz: "negoti-", decl: "2.ª", genero: "n", trad: "negocio" },
  { lema: "nēmō", tipo: "sustantivo", raiz: "nemin-", decl: "3.ª", genero: "m", trad: "nadie" },
  { lema: "Neptūnus", tipo: "sustantivo", raiz: "Neptun-", decl: "2.ª", genero: "m", trad: "Neptuno" },
  { lema: "nihil", tipo: "sustantivo", raiz: "nihil", decl: "Indeclinable", genero: "n", trad: "nada" },
  { lema: "novācula", tipo: "sustantivo", raiz: "novacul-", decl: "1.ª", genero: "f", trad: "navaja" },
  { lema: "nox", tipo: "sustantivo", raiz: "noct-", decl: "3.ª", genero: "f", trad: "noche" },
  { lema: "nūbēs", tipo: "sustantivo", raiz: "nub-", decl: "3.ª", genero: "f", trad: "nube" },
  { lema: "Nūceria", tipo: "sustantivo", raiz: "Nuceri-", decl: "1.ª", genero: "f", trad: "Nuceria" },
  { lema: "Nūcerīnī", tipo: "sustantivo", raiz: "Nucerin-", decl: "2.ª", genero: "m", trad: "nucerinos" },
  { lema: "nūntius", tipo: "sustantivo", raiz: "nunti-", decl: "2.ª", genero: "m", trad: "mensajero" },
  { lema: "oleum", tipo: "sustantivo", raiz: "ole-", decl: "2.ª", genero: "n", trad: "aceite" },
  { lema: "ōrātiō", tipo: "sustantivo", raiz: "oration-", decl: "3.ª", genero: "f", trad: "discurso" },
  { lema: "Orcus", tipo: "sustantivo", raiz: "Orc-", decl: "2.ª", genero: "m", trad: "Inframundo" },
  { lema: "ōrnātrīx", tipo: "sustantivo", raiz: "ornatric-", decl: "3.ª", genero: "f", trad: "peluquera" },
  { lema: "palaestra", tipo: "sustantivo", raiz: "palaestr-", decl: "1.ª", genero: "f", trad: "palestra" },
  { lema: "pānis", tipo: "sustantivo", raiz: "pan-", decl: "3.ª", genero: "m", trad: "pan" },
  { lema: "Pantagathus", tipo: "sustantivo", raiz: "Pantagath-", decl: "2.ª", genero: "m", trad: "Pantagato" },
  { lema: "parēns", tipo: "sustantivo", raiz: "parent-", decl: "3.ª", genero: "m", trad: "padre/madre" },
  { lema: "pariēs", tipo: "sustantivo", raiz: "pariet-", decl: "3.ª", genero: "m", trad: "pared" },
  { lema: "pāstor", tipo: "sustantivo", raiz: "pastor-", decl: "3.ª", genero: "m", trad: "pastor" },
  { lema: "pater", tipo: "sustantivo", raiz: "patr-", decl: "3.ª", genero: "m", trad: "padre" },
  { lema: "pauper", tipo: "sustantivo", raiz: "pauper-", decl: "3.ª", genero: "m", trad: "pobre" },
  { lema: "pāvō", tipo: "sustantivo", raiz: "pavon-", decl: "3.ª", genero: "m", trad: "pavo real" },
  { lema: "pavor", tipo: "sustantivo", raiz: "pavor-", decl: "3.ª", genero: "m", trad: "pavor" },
  { lema: "pāx", tipo: "sustantivo", raiz: "pac-", decl: "3.ª", genero: "f", trad: "paz" },
  { lema: "pecūnia", tipo: "sustantivo", raiz: "pecuni-", decl: "1.ª", genero: "f", trad: "dinero" },
  { lema: "pēs", tipo: "sustantivo", raiz: "ped-", decl: "3.ª", genero: "m", trad: "pie" },
  { lema: "pestis", tipo: "sustantivo", raiz: "pest-", decl: "3.ª", genero: "f", trad: "peste" },
  { lema: "philosophus", tipo: "sustantivo", raiz: "philosoph-", decl: "2.ª", genero: "m", trad: "filósofo" },
  { lema: "pictūra", tipo: "sustantivo", raiz: "pictur-", decl: "1.ª", genero: "f", trad: "pintura" },
  { lema: "piscīna", tipo: "sustantivo", raiz: "piscin-", decl: "1.ª", genero: "f", trad: "piscina" },
  { lema: "pistor", tipo: "sustantivo", raiz: "pistor-", decl: "3.ª", genero: "m", trad: "panadero" },
  { lema: "pōculum", tipo: "sustantivo", raiz: "pocul-", decl: "2.ª", genero: "n", trad: "copa" },
  { lema: "poēta", tipo: "sustantivo", raiz: "poet-", decl: "1.ª", genero: "m", trad: "poeta" },
  { lema: "pollex", tipo: "sustantivo", raiz: "pollic-", decl: "3.ª", genero: "m", trad: "pulgar" },
  { lema: "Pompōniānus", tipo: "sustantivo", raiz: "Pomponian-", decl: "2.ª", genero: "m", trad: "Pomponiano" },
  { lema: "pōns", tipo: "sustantivo", raiz: "pont-", decl: "3.ª", genero: "m", trad: "puente" },
  { lema: "Poppaea", tipo: "sustantivo", raiz: "Poppae-", decl: "1.ª", genero: "f", trad: "Popea" },
  { lema: "porta", tipo: "sustantivo", raiz: "port-", decl: "1.ª", genero: "f", trad: "puerta" },
  { lema: "porticus", tipo: "sustantivo", raiz: "portic-", decl: "4.ª", genero: "f", trad: "pórtico" },
  { lema: "portus", tipo: "sustantivo", raiz: "port-", decl: "4.ª", genero: "m", trad: "puerto" },
  { lema: "praemium", tipo: "sustantivo", raiz: "praemi-", decl: "2.ª", genero: "n", trad: "premio" },
  { lema: "Prīscus", tipo: "sustantivo", raiz: "Prisc-", decl: "2.ª", genero: "m", trad: "Prisco" },
  { lema: "Prūdēns", tipo: "sustantivo", raiz: "Prudent-", decl: "3.ª", genero: "m", trad: "Prudente" },
  { lema: "puella", tipo: "sustantivo", raiz: "puell-", decl: "1.ª", genero: "f", trad: "niña" },

  // BLOQUE 3
  { lema: "puer", tipo: "sustantivo", raiz: "puer-", decl: "2.ª", genero: "m", trad: "niño" },
  { lema: "pugil", tipo: "sustantivo", raiz: "pugil-", decl: "3.ª", genero: "m", trad: "boxeador" },
  { lema: "pugna", tipo: "sustantivo", raiz: "pugn-", decl: "1.ª", genero: "f", trad: "pelea" },
  { lema: "Pugnāx", tipo: "sustantivo", raiz: "Pugnac-", decl: "3.ª", genero: "m", trad: "Pugnax" },
  { lema: "pȳramis", tipo: "sustantivo", raiz: "pyramid-", decl: "3.ª", genero: "f", trad: "pirámide" },
  { lema: "Quīntus", tipo: "sustantivo", raiz: "Quint-", decl: "2.ª", genero: "m", trad: "Quinto" },
  { lema: "Rēgulus", tipo: "sustantivo", raiz: "Regul-", decl: "2.ª", genero: "m", trad: "Régulo" },
  { lema: "rēs", tipo: "sustantivo", raiz: "r-", decl: "5.ª", genero: "f", trad: "cosa" },
  { lema: "rex", tipo: "sustantivo", raiz: "reg-", decl: "3.ª", genero: "f", trad: "rey" },
  { lema: "rētiārius", tipo: "sustantivo", raiz: "retiari-", decl: "2.ª", genero: "m", trad: "reciario" },
  { lema: "rhētor", tipo: "sustantivo", raiz: "rhetor-", decl: "3.ª", genero: "m", trad: "maestro" },
  { lema: "Rōma", tipo: "sustantivo", raiz: "Rom-", decl: "1.ª", genero: "f", trad: "Roma" },
  { lema: "ruīna", tipo: "sustantivo", raiz: "ruin-", decl: "1.ª", genero: "f", trad: "ruina" },
  { lema: "sacrificium", tipo: "sustantivo", raiz: "sacrifici-", decl: "2.ª", genero: "n", trad: "sacrificio" },
  { lema: "sanguis", tipo: "sustantivo", raiz: "sanguin-", decl: "3.ª", genero: "m", trad: "sangre" },
  { lema: "scaena", tipo: "sustantivo", raiz: "scaen-", decl: "1.ª", genero: "f", trad: "escenario" },
  { lema: "Sceledrus", tipo: "sustantivo", raiz: "Sceledr-", decl: "2.ª", genero: "m", trad: "Escéledro" },
  { lema: "scrīptor", tipo: "sustantivo", raiz: "scriptor-", decl: "3.ª", genero: "m", trad: "escritor" },
  { lema: "sella", tipo: "sustantivo", raiz: "sell-", decl: "1.ª", genero: "f", trad: "silla" },
  { lema: "senātor", tipo: "sustantivo", raiz: "senator-", decl: "3.ª", genero: "m", trad: "senador" },
  { lema: "senex", tipo: "sustantivo", raiz: "sen-", decl: "3.ª", genero: "m", trad: "anciano" },
  { lema: "sententia", tipo: "sustantivo", raiz: "sententi-", decl: "1.ª", genero: "f", trad: "opinión" },
  { lema: "serpēns", tipo: "sustantivo", raiz: "serpent-", decl: "3.ª", genero: "f", trad: "serpiente" },
  { lema: "servus", tipo: "sustantivo", raiz: "serv-", decl: "2.ª", genero: "m", trad: "esclavo" },
  { lema: "signum", tipo: "sustantivo", raiz: "sign-", decl: "2.ª", genero: "n", trad: "señal" },
  { lema: "silva", tipo: "sustantivo", raiz: "silv-", decl: "1.ª", genero: "f", trad: "bosque" },
  { lema: "sonus", tipo: "sustantivo", raiz: "son-", decl: "2.ª", genero: "m", trad: "sonido" },
  { lema: "Sorex", tipo: "sustantivo", raiz: "Soric-", decl: "3.ª", genero: "m", trad: "Sórex" },
  { lema: "soror", tipo: "sustantivo", raiz: "soror-", decl: "3.ª", genero: "f", trad: "hermana" },
  { lema: "spectāculum", tipo: "sustantivo", raiz: "spectacul-", decl: "2.ª", genero: "n", trad: "espectáculo" },
  { lema: "spectātor", tipo: "sustantivo", raiz: "spectator-", decl: "3.ª", genero: "m", trad: "espectador" },
  { lema: "spīna", tipo: "sustantivo", raiz: "spin-", decl: "1.ª", genero: "f", trad: "espina" },
  { lema: "Spurius", tipo: "sustantivo", raiz: "Spuri-", decl: "2.ª", genero: "m", trad: "Spurio" },
  { lema: "statua", tipo: "sustantivo", raiz: "statu-", decl: "1.ª", genero: "f", trad: "estatua" },
  { lema: "stēlla", tipo: "sustantivo", raiz: "stell-", decl: "1.ª", genero: "f", trad: "estrella" },
  { lema: "stola", tipo: "sustantivo", raiz: "stol-", decl: "1.ª", genero: "f", trad: "estola" },
  { lema: "strigil", tipo: "sustantivo", raiz: "strigil-", decl: "3.ª", genero: "f", trad: "estrígil" },
  { lema: "Sulla", tipo: "sustantivo", raiz: "Sull-", decl: "1.ª", genero: "m", trad: "Sila" },
  { lema: "Syphāx", tipo: "sustantivo", raiz: "Syphac-", decl: "3.ª", genero: "m", trad: "Sífax" },
  { lema: "taberna", tipo: "sustantivo", raiz: "tabern-", decl: "1.ª", genero: "f", trad: "taberna" },
  { lema: "tablīnum", tipo: "sustantivo", raiz: "tablin-", decl: "2.ª", genero: "n", trad: "despacho" },
  { lema: "templum", tipo: "sustantivo", raiz: "templ-", decl: "2.ª", genero: "n", trad: "templo" },
{ 
  lema: "tempus", 
  tipo: "sustantivo", 
  raiz: "tempor-", 
  decl: "3.ª", 
  genero: "n", 
  trad: "tiempo" 
},
  { lema: "tepidārium", tipo: "sustantivo", raiz: "tepidari-", decl: "2.ª", genero: "n", trad: "tepidarium" },
  { lema: "terra", tipo: "sustantivo", raiz: "terr-", decl: "1.ª", genero: "f", trad: "tierra" },
  { lema: "testis", tipo: "sustantivo", raiz: "test-", decl: "3.ª", genero: "m", trad: "testigo" },
  { lema: "theātrum", tipo: "sustantivo", raiz: "theatr-", decl: "2.ª", genero: "n", trad: "teatro" },
  { lema: "Theodōrus", tipo: "sustantivo", raiz: "Theodor-", decl: "2.ª", genero: "m", trad: "Teodoro" },
  { lema: "thermae", tipo: "sustantivo", raiz: "therm-", decl: "1.ª", genero: "f", trad: "termas" },
  { lema: "Thrasymachus", tipo: "sustantivo", raiz: "Thrasymach-", decl: "2.ª", genero: "m", trad: "Trasímaco" },
  { lema: "titulus", tipo: "sustantivo", raiz: "titul-", decl: "2.ª", genero: "m", trad: "título" },
  { lema: "toga", tipo: "sustantivo", raiz: "tog-", decl: "1.ª", genero: "f", trad: "toga" },
  { lema: "tōnsor", tipo: "sustantivo", raiz: "tonsor-", decl: "3.ª", genero: "m", trad: "barbero" },
  { lema: "tremor", tipo: "sustantivo", raiz: "tremor-", decl: "3.ª", genero: "m", trad: "temblor" },
  { lema: "triclīnium", tipo: "sustantivo", raiz: "triclini-", decl: "2.ª", genero: "n", trad: "triclinio" },
  { lema: "tuba", tipo: "sustantivo", raiz: "tub-", decl: "1.ª", genero: "f", trad: "trompeta" },
  { lema: "tunica", tipo: "sustantivo", raiz: "tunic-", decl: "1.ª", genero: "f", trad: "túnica" },
  { lema: "turba", tipo: "sustantivo", raiz: "turb-", decl: "1.ª", genero: "f", trad: "multitud" },
  { lema: "umbra", tipo: "sustantivo", raiz: "umbr-", decl: "1.ª", genero: "f", trad: "sombra" },
  { lema: "Umbricius", tipo: "sustantivo", raiz: "Umbrici-", decl: "2.ª", genero: "m", trad: "Umbricio" },
  { lema: "urbs", tipo: "sustantivo", raiz: "urb-", decl: "3.ª", genero: "f", trad: "ciudad" },
  { lema: "uxor", tipo: "sustantivo", raiz: "uxor-", decl: "3.ª", genero: "f", trad: "esposa" },
  { lema: "vēnābulum", tipo: "sustantivo", raiz: "venabul-", decl: "2.ª", genero: "n", trad: "venablo" },
  { lema: "vēnālīcius", tipo: "sustantivo", raiz: "venalici-", decl: "2.ª", genero: "m", trad: "vendedor esclavos" },
  { lema: "vēnātiō", tipo: "sustantivo", raiz: "venation-", decl: "3.ª", genero: "f", trad: "caza" },
  { lema: "versipellis", tipo: "sustantivo", raiz: "versipell-", decl: "3.ª", genero: "m", trad: "hombre lobo" },
  { lema: "versus", tipo: "sustantivo", raiz: "vers-", decl: "4.ª", genero: "m", trad: "verso" }, // Nota: 4ta
  { lema: "Vesuvius", tipo: "sustantivo", raiz: "Vesuvi-", decl: "2.ª", genero: "m", trad: "Vesubio" },
  { lema: "via", tipo: "sustantivo", raiz: "vi-", decl: "1.ª", genero: "f", trad: "vía" },
  { lema: "victor", tipo: "sustantivo", raiz: "victor-", decl: "3.ª", genero: "m", trad: "vencedor" },
  { lema: "vīlicus", tipo: "sustantivo", raiz: "vilic-", decl: "2.ª", genero: "m", trad: "capataz" },
  { lema: "vīlla", tipo: "sustantivo", raiz: "vill-", decl: "1.ª", genero: "f", trad: "villa" },
  { lema: "vīnum", tipo: "sustantivo", raiz: "vin-", decl: "2.ª", genero: "n", trad: "vino" },
  { lema: "vir", tipo: "sustantivo", raiz: "vir-", decl: "2.ª", genero: "m", trad: "hombre" },
  { lema: "vīta", tipo: "sustantivo", raiz: "vit-", decl: "1.ª", genero: "f", trad: "vida" }
];