const verbos = [
  { lema: "accūsat", tipo: "verbo", raiz: "accusa-", conj: "1.ª", trad: "acusa" },
  { lema: "aberat", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "estaba ausente" },
  { lema: "abest", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "está ausente" },
  { lema: "abit", tipo: "verbo", raiz: "eo", conj: "Irregular", trad: "se va" },
  { lema: "accidit", tipo: "verbo", raiz: "accid-", conj: "3.ª", trad: "sucedió" },
  { lema: "accipit", tipo: "verbo", raiz: "accip-", conj: "3.ª (Mixta)", trad: "acepta" },
  { lema: "aderat", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "estaba presente" },
  { lema: "adest", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "está presente" },
  { lema: "adiuvat", tipo: "verbo", raiz: "adiuva-", conj: "1.ª", trad: "ayuda" },
  { lema: "administrat", tipo: "verbo", raiz: "administra-", conj: "1.ª", trad: "administra" },
  { lema: "adsunt", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "están presentes" },
  { lema: "aedificat", tipo: "verbo", raiz: "aedifica-", conj: "1.ª", trad: "construye" },
  { lema: "agit", tipo: "verbo", raiz: "ag-", conj: "3.ª", trad: "hace, actúa" },
  { lema: "agitat", tipo: "verbo", raiz: "agita-", conj: "1.ª", trad: "persigue" },
  { lema: "agnōscit", tipo: "verbo", raiz: "agnosc-", conj: "3.ª", trad: "reconoce" },
  { lema: "amat", tipo: "verbo", raiz: "ama-", conj: "1.ª", trad: "ama" },
  { lema: "ambulat", tipo: "verbo", raiz: "ambula-", conj: "1.ª", trad: "camina" },
  { lema: "āmīsit", tipo: "verbo", raiz: "amitt-", conj: "3.ª", trad: "perdió" },
  { lema: "aperit", tipo: "verbo", raiz: "aperi-", conj: "4.ª", trad: "abre" },
  { lema: "appāret", tipo: "verbo", raiz: "appare-", conj: "2.ª", trad: "aparece" },
  { lema: "ardet", tipo: "verbo", raiz: "arde-", conj: "2.ª", trad: "arde" },
  { lema: "audit", tipo: "verbo", raiz: "audi-", conj: "4.ª", trad: "oye" },
  { lema: "bibit", tipo: "verbo", raiz: "bib-", conj: "3.ª", trad: "bebe" },
  { lema: "cantat", tipo: "verbo", raiz: "canta-", conj: "1.ª", trad: "canta" },
  { lema: "capit", tipo: "verbo", raiz: "cap-", conj: "3.ª (Mixta)", trad: "captura" },
  { lema: "cavē", tipo: "verbo", raiz: "cave-", conj: "2.ª", trad: "¡cuidado!" },
  { lema: "cecidit", tipo: "verbo", raiz: "cad-", conj: "3.ª", trad: "cayó" },
  { lema: "cēlat", tipo: "verbo", raiz: "cela-", conj: "1.ª", trad: "esconde" },
  { lema: "celebrat", tipo: "verbo", raiz: "celebra-", conj: "1.ª", trad: "celebra" },
  { lema: "cēnat", tipo: "verbo", raiz: "cena-", conj: "1.ª", trad: "cena" },
  { lema: "circumspectat", tipo: "verbo", raiz: "circumspecta-", conj: "1.ª", trad: "mira alrededor" },
  { lema: "clāmat", tipo: "verbo", raiz: "clama-", conj: "1.ª", trad: "grita" },
  { lema: "commīsit", tipo: "verbo", raiz: "committ-", conj: "3.ª", trad: "comenzó" },
  { lema: "complet", tipo: "verbo", raiz: "comple-", conj: "2.ª", trad: "llena" },
  { lema: "compōnit", tipo: "verbo", raiz: "compon-", conj: "3.ª", trad: "arregla" },
  { lema: "comprehendit", tipo: "verbo", raiz: "comprehend-", conj: "3.ª", trad: "arrestó" },
  { lema: "cōnsentit", tipo: "verbo", raiz: "consenti-", conj: "4.ª", trad: "está de acuerdo" },
  { lema: "cōnspicit", tipo: "verbo", raiz: "conspic-", conj: "3.ª (Mixta)", trad: "divisa" },
  { lema: "cōnsūmit", tipo: "verbo", raiz: "consum-", conj: "3.ª", trad: "consume" },
  { lema: "contendit", tipo: "verbo", raiz: "contend-", conj: "3.ª", trad: "se apresura" },
  { lema: "convenit", tipo: "verbo", raiz: "conveni-", conj: "4.ª", trad: "se reúne" },
  { lema: "convincit", tipo: "verbo", raiz: "convinc-", conj: "3.ª", trad: "declara culpable" },
  { lema: "coquit", tipo: "verbo", raiz: "coqu-", conj: "3.ª", trad: "cocina" },
  { lema: "corrigit", tipo: "verbo", raiz: "corrig-", conj: "3.ª", trad: "corrige" },
  { lema: "crēdit", tipo: "verbo", raiz: "cred-", conj: "3.ª", trad: "cree" },
  { lema: "cupit", tipo: "verbo", raiz: "cup-", conj: "3.ª (Mixta)", trad: "desea" },
  { lema: "cūrat", tipo: "verbo", raiz: "cura-", conj: "1.ª", trad: "cuida" },
  { lema: "currit", tipo: "verbo", raiz: "curr-", conj: "3.ª", trad: "corre" },
  { lema: "custōdit", tipo: "verbo", raiz: "custodi-", conj: "4.ª", trad: "vigila" },
  { lema: "dat", tipo: "verbo", raiz: "da-", conj: "1.ª (Irreg)", trad: "da" },
  { lema: "dēbet", tipo: "verbo", raiz: "debe-", conj: "2.ª", trad: "debe" },
  { lema: "dēcipit", tipo: "verbo", raiz: "decip-", conj: "3.ª (Mixta)", trad: "engaña" },
  { lema: "dēiēcit", tipo: "verbo", raiz: "deic-", conj: "3.ª (Mixta)", trad: "arrojó" },
  { lema: "dēlectat", tipo: "verbo", raiz: "delecta-", conj: "1.ª", trad: "deleita" },
  { lema: "dēlēvit", tipo: "verbo", raiz: "dele-", conj: "2.ª", trad: "destruyó" },
  { lema: "dēpōnit", tipo: "verbo", raiz: "depon-", conj: "3.ª", trad: "deposita" },
  { lema: "dēscendit", tipo: "verbo", raiz: "descend-", conj: "3.ª", trad: "desciende" },
  { lema: "dēsiste", tipo: "verbo", raiz: "desist-", conj: "3.ª", trad: "¡para!" },
  { lema: "dēspērat", tipo: "verbo", raiz: "despera-", conj: "1.ª", trad: "desespera" },
  { lema: "dēstrīnxit", tipo: "verbo", raiz: "destring-", conj: "3.ª", trad: "desenvainó" },
  { lema: "dīcit", tipo: "verbo", raiz: "dic-", conj: "3.ª", trad: "dice" },
  { lema: "dictat", tipo: "verbo", raiz: "dicta-", conj: "1.ª", trad: "dicta" },
  { lema: "discēdit", tipo: "verbo", raiz: "disced-", conj: "3.ª", trad: "se marcha" },
  { lema: "discit", tipo: "verbo", raiz: "disc-", conj: "3.ª", trad: "aprende" },
  { lema: "dissentit", tipo: "verbo", raiz: "dissenti-", conj: "4.ª", trad: "disiente" },
  { lema: "docet", tipo: "verbo", raiz: "doce-", conj: "2.ª", trad: "enseña" },
  { lema: "dolet", tipo: "verbo", raiz: "dole-", conj: "2.ª", trad: "duele" },
  { lema: "dormit", tipo: "verbo", raiz: "dormi-", conj: "4.ª", trad: "duerme" },
  { lema: "dūcit", tipo: "verbo", raiz: "duc-", conj: "3.ª", trad: "conduce" },
  { lema: "ēdit", tipo: "verbo", raiz: "ed-", conj: "3.ª", trad: "presenta" },
  { lema: "effūgit", tipo: "verbo", raiz: "effug-", conj: "3.ª (Mixta)", trad: "escapó" },
  { lema: "ēlēgit", tipo: "verbo", raiz: "elig-", conj: "3.ª", trad: "eligió" },
  { lema: "emit", tipo: "verbo", raiz: "em-", conj: "3.ª", trad: "compra" },
  { lema: "ēmittit", tipo: "verbo", raiz: "emitt-", conj: "3.ª", trad: "envía" },
  { lema: "ērāde", tipo: "verbo", raiz: "erad-", conj: "3.ª", trad: "¡borra!" },
  { lema: "erant", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "eran" },
  { lema: "ērāsit", tipo: "verbo", raiz: "erad-", conj: "3.ª", trad: "borró" },
  { lema: "erat", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "era" },
  { lema: "ērubēscit", tipo: "verbo", raiz: "erubesc-", conj: "3.ª", trad: "se sonroja" },
  { lema: "es", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "eres" },
  { lema: "est", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "es" },
  { lema: "estis", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "sois" },
  { lema: "ēsurit", tipo: "verbo", raiz: "esuri-", conj: "4.ª", trad: "tiene hambre" },
  { lema: "ēvānuit", tipo: "verbo", raiz: "evanesc-", conj: "3.ª", trad: "se desvaneció" },
  { lema: "ēvītāvit", tipo: "verbo", raiz: "evita-", conj: "1.ª", trad: "evitó" },
  { lema: "ēvolāvit", tipo: "verbo", raiz: "evola-", conj: "1.ª", trad: "voló" },
  { lema: "excitāvit", tipo: "verbo", raiz: "excita-", conj: "1.ª", trad: "despertó" },
  { lema: "exclāmāvit", tipo: "verbo", raiz: "exclama-", conj: "1.ª", trad: "exclamó" },
  { lema: "exercet", tipo: "verbo", raiz: "exerce-", conj: "2.ª", trad: "ejercita" },
  { lema: "exit", tipo: "verbo", raiz: "eo", conj: "Irregular", trad: "sale" },
  { lema: "explicat", tipo: "verbo", raiz: "explica-", conj: "1.ª", trad: "explica" },
  { lema: "explicāvit", tipo: "verbo", raiz: "explica-", conj: "1.ª", trad: "explicó" },
  { lema: "exspectat", tipo: "verbo", raiz: "exspecta-", conj: "1.ª", trad: "espera" },
  { lema: "exspīrāvit", tipo: "verbo", raiz: "exspira-", conj: "1.ª", trad: "expiró" },
  { lema: "extrāxit", tipo: "verbo", raiz: "extrah-", conj: "3.ª", trad: "extrajo" },
  { lema: "facit", tipo: "verbo", raiz: "fac-", conj: "3.ª (Mixta)", trad: "hace" },
  { lema: "favet", tipo: "verbo", raiz: "fave-", conj: "2.ª", trad: "favorece" },
  { lema: "fert", tipo: "verbo", raiz: "fero", conj: "Irregular", trad: "lleva" },
  { lema: "festīnat", tipo: "verbo", raiz: "festina-", conj: "1.ª", trad: "se apresura" },
  { lema: "fluit", tipo: "verbo", raiz: "flu-", conj: "3.ª", trad: "fluye" },
  { lema: "fugit", tipo: "verbo", raiz: "fug-", conj: "3.ª (Mixta)", trad: "huye" },
  { lema: "garrit", tipo: "verbo", raiz: "garri-", conj: "4.ª", trad: "parlotea" },
  { lema: "gerit", tipo: "verbo", raiz: "ger-", conj: "3.ª", trad: "lleva puesto" },
  { lema: "gustat", tipo: "verbo", raiz: "gusta-", conj: "1.ª", trad: "gusta" },
  { lema: "habet", tipo: "verbo", raiz: "habe-", conj: "2.ª", trad: "tiene" },
  { lema: "habitat", tipo: "verbo", raiz: "habita-", conj: "1.ª", trad: "habita" },
  { lema: "hausit", tipo: "verbo", raiz: "hauri-", conj: "4.ª", trad: "drenó" },
  { lema: "iacet", tipo: "verbo", raiz: "iace-", conj: "2.ª", trad: "yace" },
  { lema: "ībat", tipo: "verbo", raiz: "eo", conj: "Irregular", trad: "iba" },
  { lema: "imprimit", tipo: "verbo", raiz: "imprim-", conj: "3.ª", trad: "imprime" },
  { lema: "incidit", tipo: "verbo", raiz: "incid-", conj: "3.ª", trad: "cae" },
  { lema: "incitat", tipo: "verbo", raiz: "incita-", conj: "1.ª", trad: "incita" },
  { lema: "induit", tipo: "verbo", raiz: "indu-", conj: "3.ª", trad: "se puso" },
  { lema: "inquit", tipo: "verbo", raiz: "inquam", conj: "Defectivo", trad: "dice / dijo" },
  { lema: "īnspicit", tipo: "verbo", raiz: "inspic-", conj: "3.ª (Mixta)", trad: "inspecciona" },
  { lema: "intellegit", tipo: "verbo", raiz: "intelleg-", conj: "3.ª", trad: "entiende" },
  { lema: "interfēcit", tipo: "verbo", raiz: "interfic-", conj: "3.ª (Mixta)", trad: "mató" },
  { lema: "intrat", tipo: "verbo", raiz: "intra-", conj: "1.ª", trad: "entra" },
  { lema: "invenit", tipo: "verbo", raiz: "inveni-", conj: "4.ª", trad: "encuentra" },
  { lema: "invītat", tipo: "verbo", raiz: "invita-", conj: "1.ª", trad: "invita" },
  { lema: "iubet", tipo: "verbo", raiz: "iube-", conj: "2.ª", trad: "ordena" },
  { lema: "labōrat", tipo: "verbo", raiz: "labora-", conj: "1.ª", trad: "trabaja" },
  { lema: "lacrimat", tipo: "verbo", raiz: "lacrima-", conj: "1.ª", trad: "llora" },
  { lema: "lambit", tipo: "verbo", raiz: "lamb-", conj: "3.ª", trad: "lame" },
  { lema: "lātrat", tipo: "verbo", raiz: "latra-", conj: "1.ª", trad: "ladra" },
  { lema: "laudat", tipo: "verbo", raiz: "lauda-", conj: "1.ª", trad: "alaba" },
  { lema: "legit", tipo: "verbo", raiz: "leg-", conj: "3.ª", trad: "lee" },
  { lema: "līberāvit", tipo: "verbo", raiz: "libera-", conj: "1.ª", trad: "liberó" },
  { lema: "lūcet", tipo: "verbo", raiz: "luce-", conj: "2.ª", trad: "brilla" },
  { lema: "manet", tipo: "verbo", raiz: "mane-", conj: "2.ª", trad: "permanece" },
  { lema: "mittit", tipo: "verbo", raiz: "mitt-", conj: "3.ª", trad: "envía" },
  { lema: "moritūrus", tipo: "verbo", raiz: "mori-", conj: "3.ª (Deponente)", trad: "que va a morir" },
  { lema: "nārrat", tipo: "verbo", raiz: "narra-", conj: "1.ª", trad: "narra" },
  { lema: "necat", tipo: "verbo", raiz: "neca-", conj: "1.ª", trad: "mata" },
  { lema: "numerat", tipo: "verbo", raiz: "numera-", conj: "1.ª", trad: "cuenta" },
  { lema: "nūntiat", tipo: "verbo", raiz: "nuntia-", conj: "1.ª", trad: "anuncia" },
  { lema: "obdormīvit", tipo: "verbo", raiz: "obdormi-", conj: "4.ª", trad: "se durmió" },
  { lema: "offert", tipo: "verbo", raiz: "fero", conj: "Irregular", trad: "ofrece" },
  { lema: "olfēcit", tipo: "verbo", raiz: "olfac-", conj: "3.ª (Mixta)", trad: "olió" },
  { lema: "ostendit", tipo: "verbo", raiz: "ostend-", conj: "3.ª", trad: "muestra" },
  { lema: "parat", tipo: "verbo", raiz: "para-", conj: "1.ª", trad: "prepara" },
  { lema: "parce", tipo: "verbo", raiz: "parc-", conj: "3.ª", trad: "¡perdona!" },
  { lema: "percussit", tipo: "verbo", raiz: "percut-", conj: "3.ª (Mixta)", trad: "golpeó" },
  { lema: "periit", tipo: "verbo", raiz: "eo (pereo)", conj: "Irregular", trad: "murió" },
  { lema: "pervēnit", tipo: "verbo", raiz: "perveni-", conj: "4.ª", trad: "llegó" },
  { lema: "petit", tipo: "verbo", raiz: "pet-", conj: "3.ª", trad: "ataca / pide" },
  { lema: "pingit", tipo: "verbo", raiz: "ping-", conj: "3.ª", trad: "pinta" },
  { lema: "placet", tipo: "verbo", raiz: "place-", conj: "2.ª", trad: "place" },
  { lema: "plaudit", tipo: "verbo", raiz: "plaud-", conj: "3.ª", trad: "aplaude" },
{ 
  lema: "ponit", 
  tipo: "verbo", 
  raiz: "pon-", 
  conj: "3.ª", 
  trad: "pone" 
},
  { lema: "portat", tipo: "verbo", raiz: "porta-", conj: "1.ª", trad: "lleva" },
  { lema: "postulat", tipo: "verbo", raiz: "postula-", conj: "1.ª", trad: "exige" },
  { lema: "posuit", tipo: "verbo", raiz: "pon-", conj: "3.ª", trad: "puso" },
  { lema: "probat", tipo: "verbo", raiz: "proba-", conj: "1.ª", trad: "prueba" },
  { lema: "prōcēdit", tipo: "verbo", raiz: "proced-", conj: "3.ª", trad: "avanza" },
  { lema: "prōmittit", tipo: "verbo", raiz: "promitt-", conj: "3.ª", trad: "promete" },
  { lema: "prōvocāvit", tipo: "verbo", raiz: "provoca-", conj: "1.ª", trad: "desafió" },
  { lema: "pugnat", tipo: "verbo", raiz: "pugna-", conj: "1.ª", trad: "lucha" },
  { lema: "pulsat", tipo: "verbo", raiz: "pulsa-", conj: "1.ª", trad: "golpea" },
  { lema: "quaerit", tipo: "verbo", raiz: "quaer-", conj: "3.ª", trad: "busca" },
  { lema: "rādit", tipo: "verbo", raiz: "rad-", conj: "3.ª", trad: "raspa" },
  { lema: "rapuit", tipo: "verbo", raiz: "rap-", conj: "3.ª (Mixta)", trad: "raptó" },
  { lema: "recitat", tipo: "verbo", raiz: "recita-", conj: "1.ª", trad: "recita" },
  { lema: "recumbit", tipo: "verbo", raiz: "recumb-", conj: "3.ª", trad: "se recuesta" },
  { lema: "recūsāvit", tipo: "verbo", raiz: "recusa-", conj: "1.ª", trad: "rechazó" },
  { lema: "reddit", tipo: "verbo", raiz: "redd-", conj: "3.ª", trad: "devuelve" },
  { lema: "rediit", tipo: "verbo", raiz: "eo (redeo)", conj: "Irregular", trad: "regresó" },
  { lema: "respīrāvit", tipo: "verbo", raiz: "respira-", conj: "1.ª", trad: "recuperó aliento" },
  { lema: "respondet", tipo: "verbo", raiz: "responde-", conj: "2.ª", trad: "responde" },
  { lema: "retinet", tipo: "verbo", raiz: "retine-", conj: "2.ª", trad: "retiene" },
  { lema: "revenit", tipo: "verbo", raiz: "reveni-", conj: "4.ª", trad: "regresa" },
  { lema: "rīdet", tipo: "verbo", raiz: "ride-", conj: "2.ª", trad: "ríe" },
  { lema: "rogat", tipo: "verbo", raiz: "roga-", conj: "1.ª", trad: "pregunta" },
  { lema: "ruit", tipo: "verbo", raiz: "ru-", conj: "3.ª", trad: "se precipita" },
  { lema: "salit", tipo: "verbo", raiz: "sali-", conj: "4.ª", trad: "salta" },
  { lema: "salūtat", tipo: "verbo", raiz: "saluta-", conj: "1.ª", trad: "saluda" },
  { lema: "scit", tipo: "verbo", raiz: "sci-", conj: "4.ª", trad: "sabe" },
  { lema: "scrībit", tipo: "verbo", raiz: "scrib-", conj: "3.ª", trad: "escribe" },
  { lema: "secat", tipo: "verbo", raiz: "seca-", conj: "1.ª", trad: "corta" },
  { lema: "sedet", tipo: "verbo", raiz: "sede-", conj: "2.ª", trad: "está sentado" },
  { lema: "sentit", tipo: "verbo", raiz: "senti-", conj: "4.ª", trad: "siente" },
  { lema: "servat", tipo: "verbo", raiz: "serva-", conj: "1.ª", trad: "guarda" },
  { lema: "sonuit", tipo: "verbo", raiz: "sona-", conj: "1.ª", trad: "sonó" },
  { lema: "spectat", tipo: "verbo", raiz: "specta-", conj: "1.ª", trad: "mira" },
  { lema: "stat", tipo: "verbo", raiz: "sta-", conj: "1.ª", trad: "está de pie" },
  { lema: "stertit", tipo: "verbo", raiz: "stert-", conj: "3.ª", trad: "ronca" },
  { lema: "sum", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "soy/estoy" },
  { lema: "sumus", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "somos" },
  { lema: "sunt", tipo: "verbo", raiz: "sum", conj: "Irregular", trad: "son" },
  { lema: "superat", tipo: "verbo", raiz: "supera-", conj: "1.ª", trad: "supera" },
  { lema: "superfuit", tipo: "verbo", raiz: "sum (supersum)", conj: "Irregular", trad: "sobrevivió" },
  { lema: "surgit", tipo: "verbo", raiz: "surg-", conj: "3.ª", trad: "se levanta" },
  { lema: "suscipit", tipo: "verbo", raiz: "suscip-", conj: "3.ª (Mixta)", trad: "emprende" },
  { lema: "susurrāvit", tipo: "verbo", raiz: "susurra-", conj: "1.ª", trad: "susurró" },
  { lema: "tacet", tipo: "verbo", raiz: "tace-", conj: "2.ª", trad: "calla" },
  { lema: "tenet", tipo: "verbo", raiz: "tene-", conj: "2.ª", trad: "tiene" },
  { lema: "terret", tipo: "verbo", raiz: "terre-", conj: "2.ª", trad: "aterra" },
  { lema: "timet", tipo: "verbo", raiz: "time-", conj: "2.ª", trad: "teme" },
  { lema: "tondet", tipo: "verbo", raiz: "tonde-", conj: "2.ª", trad: "afeita" },
  { lema: "trādit", tipo: "verbo", raiz: "trad-", conj: "3.ª", trad: "entrega" },
  { lema: "trahit", tipo: "verbo", raiz: "trah-", conj: "3.ª", trad: "arrastra" },
  { lema: "tremuit", tipo: "verbo", raiz: "trem-", conj: "3.ª", trad: "tembló" },
  { lema: "ululat", tipo: "verbo", raiz: "ulula-", conj: "1.ª", trad: "aúlla" },
  { lema: "vāgīvit", tipo: "verbo", raiz: "vagi-", conj: "4.ª", trad: "gimió" },
  { lema: "valeō", tipo: "verbo", raiz: "vale-", conj: "2.ª", trad: "estoy bien" },
  { lema: "vēndit", tipo: "verbo", raiz: "vend-", conj: "3.ª", trad: "vende" },
  { lema: "venit", tipo: "verbo", raiz: "veni-", conj: "4.ª", trad: "viene" },
  { lema: "verberat", tipo: "verbo", raiz: "verbera-", conj: "1.ª", trad: "golpea" },
  { lema: "vertit", tipo: "verbo", raiz: "vert-", conj: "3.ª", trad: "giró" },
  { lema: "vexat", tipo: "verbo", raiz: "vexa-", conj: "1.ª", trad: "molesta" },
  { lema: "vibrat", tipo: "verbo", raiz: "vibra-", conj: "1.ª", trad: "agita" },
  { lema: "videt", tipo: "verbo", raiz: "vide-", conj: "2.ª", trad: "ve" },
  { lema: "vīsitat", tipo: "verbo", raiz: "visita-", conj: "1.ª", trad: "visita" },
  { lema: "vituperat", tipo: "verbo", raiz: "vitupera-", conj: "1.ª", trad: "regaña" },
  { lema: "vīvit", tipo: "verbo", raiz: "viv-", conj: "3.ª", trad: "vive" },
  { lema: "vocat", tipo: "verbo", raiz: "voca-", conj: "1.ª", trad: "llama" },
  { lema: "vulnerāvit", tipo: "verbo", raiz: "vulnera-", conj: "1.ª", trad: "hirió" }
];